/*
   Kafel - syscalls (m68k)
   -----------------------------------------

   Copyright 2025 Google LLC

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

*/

#include <stddef.h>

#include "../syscall.h"

#define ARG_0 0
#define ARG_1 1
#define ARG_2 2
#define ARG_3 3
#define ARG_4 4
#define ARG_5 5

const struct syscall_descriptor m68k_syscall_list[] = {
    {"restart_syscall", 0, {}},
    {"exit",
     1,
     {
         [ARG_0] = {"error_code", 4},
     }},
    {"fork", 2, {}},
    {"read",
     3,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"count", 4},
     }},
    {"write",
     4,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"count", 4},
     }},
    {"open",
     5,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"mode", 2},
     }},
    {"close",
     6,
     {
         [ARG_0] = {"fd", 4},
     }},
    {"waitpid",
     7,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"stat_addr", 4},
         [ARG_2] = {"options", 4},
     }},
    {"creat",
     8,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"mode", 2},
     }},
    {"link",
     9,
     {
         [ARG_0] = {"oldname", 4},
         [ARG_1] = {"newname", 4},
     }},
    {"unlink",
     10,
     {
         [ARG_0] = {"pathname", 4},
     }},
    {"execve",
     11,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"argv", 4},
         [ARG_2] = {"envp", 4},
     }},
    {"chdir",
     12,
     {
         [ARG_0] = {"filename", 4},
     }},
    {"time",
     13,
     {
         [ARG_0] = {"tloc", 4},
     }},
    {"mknod",
     14,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"mode", 2},
         [ARG_2] = {"dev", 4},
     }},
    {"chmod",
     15,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"mode", 2},
     }},
    {"chown16",
     16,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"user", 2},
         [ARG_2] = {"group", 2},
     }},
    {"oldstat",
     18,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"lseek",
     19,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"offset", 4},
         [ARG_2] = {"whence", 4},
     }},
    {"getpid", 20, {}},
    {"mount",
     21,
     {
         [ARG_0] = {"dev_name", 4},
         [ARG_1] = {"dir_name", 4},
         [ARG_2] = {"type", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"data", 4},
     }},
    {"umount",
     22,
     {
         [ARG_0] = {"name", 4},
     }},
    {"setuid16",
     23,
     {
         [ARG_0] = {"uid", 2},
     }},
    {"getuid16", 24, {}},
    {"stime",
     25,
     {
         [ARG_0] = {"tptr", 4},
     }},
    {"ptrace",
     26,
     {
         [ARG_0] = {"request", 4},
         [ARG_1] = {"pid", 4},
         [ARG_2] = {"addr", 4},
         [ARG_3] = {"data", 4},
     }},
    {"alarm",
     27,
     {
         [ARG_0] = {"seconds", 4},
     }},
    {"oldfstat",
     28,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"pause", 29, {}},
    {"utime",
     30,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"times", 4},
     }},
    {"access",
     33,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"mode", 4},
     }},
    {"nice",
     34,
     {
         [ARG_0] = {"increment", 4},
     }},
    {"sync", 36, {}},
    {"kill",
     37,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"sig", 4},
     }},
    {"rename",
     38,
     {
         [ARG_0] = {"oldname", 4},
         [ARG_1] = {"newname", 4},
     }},
    {"mkdir",
     39,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"mode", 2},
     }},
    {"rmdir",
     40,
     {
         [ARG_0] = {"pathname", 4},
     }},
    {"dup",
     41,
     {
         [ARG_0] = {"fildes", 4},
     }},
    {"pipe",
     42,
     {
         [ARG_0] = {"fildes", 4},
     }},
    {"times",
     43,
     {
         [ARG_0] = {"tbuf", 4},
     }},
    {"brk",
     45,
     {
         [ARG_0] = {"brk", 4},
     }},
    {"setgid16",
     46,
     {
         [ARG_0] = {"gid", 2},
     }},
    {"getgid16", 47, {}},
    {"signal",
     48,
     {
         [ARG_0] = {"sig", 4},
         [ARG_1] = {"handler", 4},
     }},
    {"geteuid16", 49, {}},
    {"getegid16", 50, {}},
    {"acct",
     51,
     {
         [ARG_0] = {"name", 4},
     }},
    {"umount2",
     52,
     {
         [ARG_0] = {"name", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"ioctl",
     54,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"arg", 4},
     }},
    {"fcntl",
     55,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"arg", 4},
     }},
    {"setpgid",
     57,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"pgid", 4},
     }},
    {"umask",
     60,
     {
         [ARG_0] = {"mask", 4},
     }},
    {"chroot",
     61,
     {
         [ARG_0] = {"filename", 4},
     }},
    {"ustat",
     62,
     {
         [ARG_0] = {"dev", 2},
         [ARG_1] = {"ubuf", 4},
     }},
    {"dup2",
     63,
     {
         [ARG_0] = {"oldfd", 4},
         [ARG_1] = {"newfd", 4},
     }},
    {"getppid", 64, {}},
    {"getpgrp", 65, {}},
    {"setsid", 66, {}},
    {"sigaction",
     67,
     {
         [ARG_0] = {"sig", 4},
         [ARG_1] = {"act", 4},
         [ARG_2] = {"oact", 4},
     }},
    {"sgetmask", 68, {}},
    {"ssetmask",
     69,
     {
         [ARG_0] = {"newmask", 4},
     }},
    {"setreuid16",
     70,
     {
         [ARG_0] = {"ruid", 2},
         [ARG_1] = {"euid", 2},
     }},
    {"setregid16",
     71,
     {
         [ARG_0] = {"rgid", 2},
         [ARG_1] = {"egid", 2},
     }},
    {"sigsuspend",
     72,
     {
         [ARG_0] = {"mask", 4},
     }},
    {"sigpending",
     73,
     {
         [ARG_0] = {"uset", 4},
     }},
    {"sethostname",
     74,
     {
         [ARG_0] = {"name", 4},
         [ARG_1] = {"len", 4},
     }},
    {"setrlimit",
     75,
     {
         [ARG_0] = {"resource", 4},
         [ARG_1] = {"rlim", 4},
     }},
    {"getrlimit",
     76,
     {
         [ARG_0] = {"resource", 4},
         [ARG_1] = {"rlim", 4},
     }},
    {"getrusage",
     77,
     {
         [ARG_0] = {"who", 4},
         [ARG_1] = {"ru", 4},
     }},
    {"gettimeofday",
     78,
     {
         [ARG_0] = {"tv", 4},
         [ARG_1] = {"tz", 4},
     }},
    {"settimeofday",
     79,
     {
         [ARG_0] = {"tv", 4},
         [ARG_1] = {"tz", 4},
     }},
    {"getgroups16",
     80,
     {
         [ARG_0] = {"gidsetsize", 4},
         [ARG_1] = {"grouplist", 4},
     }},
    {"setgroups16",
     81,
     {
         [ARG_0] = {"gidsetsize", 4},
         [ARG_1] = {"grouplist", 4},
     }},
    {"select",
     82,
     {
         [ARG_0] = {"select_struct", 4},
     }},
    {"symlink",
     83,
     {
         [ARG_0] = {"old", 4},
         [ARG_1] = {"new", 4},
     }},
    {"oldlstat",
     84,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"readlink",
     85,
     {
         [ARG_0] = {"path", 4},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"bufsiz", 4},
     }},
    {"uselib",
     86,
     {
         [ARG_0] = {"library", 4},
     }},
    {"swapon",
     87,
     {
         [ARG_0] = {"specialfile", 4},
         [ARG_1] = {"swap_flags", 4},
     }},
    {"reboot",
     88,
     {
         [ARG_0] = {"magic1", 4},
         [ARG_1] = {"magic2", 4},
         [ARG_2] = {"cmd", 4},
         [ARG_3] = {"arg", 4},
     }},
    {"readdir",
     89,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"dirent", 4},
         [ARG_2] = {"count", 4},
     }},
    {"mmap",
     90,
     {
         [ARG_0] = {"mmap_struct", 4},
     }},
    {"munmap",
     91,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"len", 4},
     }},
    {"truncate",
     92,
     {
         [ARG_0] = {"path", 4},
         [ARG_1] = {"length", 4},
     }},
    {"ftruncate",
     93,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"length", 4},
     }},
    {"fchmod",
     94,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"mode", 2},
     }},
    {"fchown16",
     95,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"user", 2},
         [ARG_2] = {"group", 2},
     }},
    {"getpriority",
     96,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"who", 4},
     }},
    {"setpriority",
     97,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"who", 4},
         [ARG_2] = {"niceval", 4},
     }},
    {"statfs",
     99,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"buf", 4},
     }},
    {"fstatfs",
     100,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buf", 4},
     }},
    {"socketcall",
     102,
     {
         [ARG_0] = {"call", 4},
         [ARG_1] = {"args", 4},
     }},
    {"syslog",
     103,
     {
         [ARG_0] = {"type", 4},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"len", 4},
     }},
    {"setitimer",
     104,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"value", 4},
         [ARG_2] = {"ovalue", 4},
     }},
    {"getitimer",
     105,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"value", 4},
     }},
    {"stat",
     106,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"lstat",
     107,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"fstat",
     108,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"vhangup", 111, {}},
    {"wait4",
     114,
     {
         [ARG_0] = {"upid", 4},
         [ARG_1] = {"stat_addr", 4},
         [ARG_2] = {"options", 4},
         [ARG_3] = {"ru", 4},
     }},
    {"swapoff",
     115,
     {
         [ARG_0] = {"specialfile", 4},
     }},
    {"sysinfo",
     116,
     {
         [ARG_0] = {"info", 4},
     }},
    {"ipc",
     117,
     {
         [ARG_0] = {"call", 4},
         [ARG_1] = {"first", 4},
         [ARG_2] = {"second", 4},
         [ARG_3] = {"third", 4},
         [ARG_4] = {"ptr", 4},
         [ARG_5] = {"fifth", 4},
     }},
    {"fsync",
     118,
     {
         [ARG_0] = {"fd", 4},
     }},
    {"sigreturn", 119, {}},
    {"clone",
     120,
     {
         [ARG_0] = {"clone_flags", 4},
         [ARG_1] = {"newsp", 4},
         [ARG_2] = {"parent_tidptr", 4},
         [ARG_3] = {"child_tidptr", 4},
         [ARG_4] = {"tls", 4},
     }},
    {"setdomainname",
     121,
     {
         [ARG_0] = {"name", 4},
         [ARG_1] = {"len", 4},
     }},
    {"uname",
     122,
     {
         [ARG_0] = {"name", 4},
     }},
    {"cacheflush",
     123,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"scope", 4},
         [ARG_2] = {"cache", 4},
         [ARG_3] = {"len", 4},
     }},
    {"adjtimex",
     124,
     {
         [ARG_0] = {"txc_p", 4},
     }},
    {"mprotect",
     125,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"prot", 4},
     }},
    {"sigprocmask",
     126,
     {
         [ARG_0] = {"how", 4},
         [ARG_1] = {"nset", 4},
         [ARG_2] = {"oset", 4},
     }},
    {"init_module",
     128,
     {
         [ARG_0] = {"umod", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"uargs", 4},
     }},
    {"delete_module",
     129,
     {
         [ARG_0] = {"name_user", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"quotactl",
     131,
     {
         [ARG_0] = {"cmd", 4},
         [ARG_1] = {"special", 4},
         [ARG_2] = {"id", 4},
         [ARG_3] = {"addr", 4},
     }},
    {"getpgid",
     132,
     {
         [ARG_0] = {"pid", 4},
     }},
    {"fchdir",
     133,
     {
         [ARG_0] = {"fd", 4},
     }},
    {"sysfs",
     135,
     {
         [ARG_0] = {"option", 4},
         [ARG_1] = {"arg1", 4},
         [ARG_2] = {"arg2", 4},
     }},
    {"personality",
     136,
     {
         [ARG_0] = {"personality", 4},
     }},
    {"setfsuid16",
     138,
     {
         [ARG_0] = {"uid", 2},
     }},
    {"setfsgid16",
     139,
     {
         [ARG_0] = {"gid", 2},
     }},
    {"_llseek",
     140,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"offset_high", 4},
         [ARG_2] = {"offset_low", 4},
         [ARG_3] = {"result", 4},
         [ARG_4] = {"whence", 4},
     }},
    {"getdents",
     141,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"dirent", 4},
         [ARG_2] = {"count", 4},
     }},
    {"_newselect",
     142,
     {
         [ARG_0] = {"n", 4},
         [ARG_1] = {"inp", 4},
         [ARG_2] = {"outp", 4},
         [ARG_3] = {"exp", 4},
         [ARG_4] = {"tvp", 4},
     }},
    {"flock",
     143,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"cmd", 4},
     }},
    {"msync",
     144,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"readv",
     145,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
     }},
    {"writev",
     146,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
     }},
    {"getsid",
     147,
     {
         [ARG_0] = {"pid", 4},
     }},
    {"fdatasync",
     148,
     {
         [ARG_0] = {"fd", 4},
     }},
    {"mlock",
     150,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
     }},
    {"munlock",
     151,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
     }},
    {"mlockall",
     152,
     {
         [ARG_0] = {"flags", 4},
     }},
    {"munlockall", 153, {}},
    {"sched_setparam",
     154,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"param", 4},
     }},
    {"sched_getparam",
     155,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"param", 4},
     }},
    {"sched_setscheduler",
     156,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"policy", 4},
         [ARG_2] = {"param", 4},
     }},
    {"sched_getscheduler",
     157,
     {
         [ARG_0] = {"pid", 4},
     }},
    {"sched_yield", 158, {}},
    {"sched_get_priority_max",
     159,
     {
         [ARG_0] = {"policy", 4},
     }},
    {"sched_get_priority_min",
     160,
     {
         [ARG_0] = {"policy", 4},
     }},
    {"sched_rr_get_interval",
     161,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"interval", 4},
     }},
    {"nanosleep",
     162,
     {
         [ARG_0] = {"rqtp", 4},
         [ARG_1] = {"rmtp", 4},
     }},
    {"mremap",
     163,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"old_len", 4},
         [ARG_2] = {"new_len", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"new_addr", 4},
     }},
    {"setresuid16",
     164,
     {
         [ARG_0] = {"ruid", 2},
         [ARG_1] = {"euid", 2},
         [ARG_2] = {"suid", 2},
     }},
    {"getresuid16",
     165,
     {
         [ARG_0] = {"ruidp", 4},
         [ARG_1] = {"euidp", 4},
         [ARG_2] = {"suidp", 4},
     }},
    {"getpagesize", 166, {}},
    {"poll",
     168,
     {
         [ARG_0] = {"ufds", 4},
         [ARG_1] = {"nfds", 4},
         [ARG_2] = {"timeout", 4},
     }},
    {"setresgid16",
     170,
     {
         [ARG_0] = {"rgid", 2},
         [ARG_1] = {"egid", 2},
         [ARG_2] = {"sgid", 2},
     }},
    {"getresgid16",
     171,
     {
         [ARG_0] = {"rgidp", 4},
         [ARG_1] = {"egidp", 4},
         [ARG_2] = {"sgidp", 4},
     }},
    {"prctl",
     172,
     {
         [ARG_0] = {"option", 4},
         [ARG_1] = {"arg2", 4},
         [ARG_2] = {"arg3", 4},
         [ARG_3] = {"arg4", 4},
         [ARG_4] = {"arg5", 4},
     }},
    {"rt_sigreturn", 173, {}},
    {"rt_sigaction",
     174,
     {
         [ARG_0] = {"sig", 4},
         [ARG_1] = {"act", 4},
         [ARG_2] = {"oact", 4},
         [ARG_3] = {"sigsetsize", 4},
     }},
    {"rt_sigprocmask",
     175,
     {
         [ARG_0] = {"how", 4},
         [ARG_1] = {"nset", 4},
         [ARG_2] = {"oset", 4},
         [ARG_3] = {"sigsetsize", 4},
     }},
    {"rt_sigpending",
     176,
     {
         [ARG_0] = {"uset", 4},
         [ARG_1] = {"sigsetsize", 4},
     }},
    {"rt_sigtimedwait",
     177,
     {
         [ARG_0] = {"uthese", 4},
         [ARG_1] = {"uinfo", 4},
         [ARG_2] = {"uts", 4},
         [ARG_3] = {"sigsetsize", 4},
     }},
    {"rt_sigqueueinfo",
     178,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"sig", 4},
         [ARG_2] = {"uinfo", 4},
     }},
    {"rt_sigsuspend",
     179,
     {
         [ARG_0] = {"unewset", 4},
         [ARG_1] = {"sigsetsize", 4},
     }},
    {"pread64",
     180,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"count", 4},
         [ARG_3] = {"pos", 8},
     }},
    {"pwrite64",
     181,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"count", 4},
         [ARG_3] = {"pos", 8},
     }},
    {"lchown16",
     182,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"user", 2},
         [ARG_2] = {"group", 2},
     }},
    {"getcwd",
     183,
     {
         [ARG_0] = {"buf", 4},
         [ARG_1] = {"size", 4},
     }},
    {"capget",
     184,
     {
         [ARG_0] = {"header", 4},
         [ARG_1] = {"dataptr", 4},
     }},
    {"capset",
     185,
     {
         [ARG_0] = {"header", 4},
         [ARG_1] = {"data", 4},
     }},
    {"sigaltstack",
     186,
     {
         [ARG_0] = {"uss", 4},
         [ARG_1] = {"uoss", 4},
     }},
    {"sendfile",
     187,
     {
         [ARG_0] = {"out_fd", 4},
         [ARG_1] = {"in_fd", 4},
         [ARG_2] = {"offset", 4},
         [ARG_3] = {"count", 4},
     }},
    {"vfork", 190, {}},
    {"ugetrlimit",
     191,
     {
         [ARG_0] = {"resource", 4},
         [ARG_1] = {"rlim", 4},
     }},
    {"mmap2",
     192,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"prot", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"fd", 4},
         [ARG_5] = {"pgoff", 4},
     }},
    {"truncate64",
     193,
     {
         [ARG_0] = {"path", 4},
         [ARG_1] = {"length", 8},
     }},
    {"ftruncate64",
     194,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"length", 8},
     }},
    {"stat64",
     195,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"lstat64",
     196,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"fstat64",
     197,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"chown",
     198,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"user", 4},
         [ARG_2] = {"group", 4},
     }},
    {"getuid", 199, {}},
    {"getgid", 200, {}},
    {"geteuid", 201, {}},
    {"getegid", 202, {}},
    {"setreuid",
     203,
     {
         [ARG_0] = {"ruid", 4},
         [ARG_1] = {"euid", 4},
     }},
    {"setregid",
     204,
     {
         [ARG_0] = {"rgid", 4},
         [ARG_1] = {"egid", 4},
     }},
    {"getgroups",
     205,
     {
         [ARG_0] = {"gidsetsize", 4},
         [ARG_1] = {"grouplist", 4},
     }},
    {"setgroups",
     206,
     {
         [ARG_0] = {"gidsetsize", 4},
         [ARG_1] = {"grouplist", 4},
     }},
    {"fchown",
     207,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"user", 4},
         [ARG_2] = {"group", 4},
     }},
    {"setresuid",
     208,
     {
         [ARG_0] = {"ruid", 4},
         [ARG_1] = {"euid", 4},
         [ARG_2] = {"suid", 4},
     }},
    {"getresuid",
     209,
     {
         [ARG_0] = {"ruidp", 4},
         [ARG_1] = {"euidp", 4},
         [ARG_2] = {"suidp", 4},
     }},
    {"setresgid",
     210,
     {
         [ARG_0] = {"rgid", 4},
         [ARG_1] = {"egid", 4},
         [ARG_2] = {"sgid", 4},
     }},
    {"getresgid",
     211,
     {
         [ARG_0] = {"rgidp", 4},
         [ARG_1] = {"egidp", 4},
         [ARG_2] = {"sgidp", 4},
     }},
    {"lchown",
     212,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"user", 4},
         [ARG_2] = {"group", 4},
     }},
    {"setuid",
     213,
     {
         [ARG_0] = {"uid", 4},
     }},
    {"setgid",
     214,
     {
         [ARG_0] = {"gid", 4},
     }},
    {"setfsuid",
     215,
     {
         [ARG_0] = {"uid", 4},
     }},
    {"setfsgid",
     216,
     {
         [ARG_0] = {"gid", 4},
     }},
    {"pivot_root",
     217,
     {
         [ARG_0] = {"new_root", 4},
         [ARG_1] = {"put_old", 4},
     }},
    {"getdents64",
     220,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"dirent", 4},
         [ARG_2] = {"count", 4},
     }},
    {"gettid", 221, {}},
    {"tkill",
     222,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"sig", 4},
     }},
    {"setxattr",
     223,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"value", 4},
         [ARG_3] = {"size", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"lsetxattr",
     224,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"value", 4},
         [ARG_3] = {"size", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"fsetxattr",
     225,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"value", 4},
         [ARG_3] = {"size", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"getxattr",
     226,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"value", 4},
         [ARG_3] = {"size", 4},
     }},
    {"lgetxattr",
     227,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"value", 4},
         [ARG_3] = {"size", 4},
     }},
    {"fgetxattr",
     228,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"value", 4},
         [ARG_3] = {"size", 4},
     }},
    {"listxattr",
     229,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"list", 4},
         [ARG_2] = {"size", 4},
     }},
    {"llistxattr",
     230,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"list", 4},
         [ARG_2] = {"size", 4},
     }},
    {"flistxattr",
     231,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"list", 4},
         [ARG_2] = {"size", 4},
     }},
    {"removexattr",
     232,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"name", 4},
     }},
    {"lremovexattr",
     233,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"name", 4},
     }},
    {"fremovexattr",
     234,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"name", 4},
     }},
    {"futex",
     235,
     {
         [ARG_0] = {"uaddr", 4},
         [ARG_1] = {"op", 4},
         [ARG_2] = {"val", 4},
         [ARG_3] = {"utime", 4},
         [ARG_4] = {"uaddr2", 4},
         [ARG_5] = {"val3", 4},
     }},
    {"sendfile64",
     236,
     {
         [ARG_0] = {"out_fd", 4},
         [ARG_1] = {"in_fd", 4},
         [ARG_2] = {"offset", 4},
         [ARG_3] = {"count", 4},
     }},
    {"mincore",
     237,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"vec", 4},
     }},
    {"madvise",
     238,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len_in", 4},
         [ARG_2] = {"behavior", 4},
     }},
    {"fcntl64",
     239,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"arg", 4},
     }},
    {"readahead",
     240,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"offset", 8},
         [ARG_2] = {"count", 4},
     }},
    {"io_setup",
     241,
     {
         [ARG_0] = {"nr_events", 4},
         [ARG_1] = {"ctxp", 4},
     }},
    {"io_destroy",
     242,
     {
         [ARG_0] = {"ctx", 4},
     }},
    {"io_getevents",
     243,
     {
         [ARG_0] = {"ctx_id", 4},
         [ARG_1] = {"min_nr", 4},
         [ARG_2] = {"nr", 4},
         [ARG_3] = {"events", 4},
         [ARG_4] = {"timeout", 4},
     }},
    {"io_submit",
     244,
     {
         [ARG_0] = {"ctx_id", 4},
         [ARG_1] = {"nr", 4},
         [ARG_2] = {"iocbpp", 4},
     }},
    {"io_cancel",
     245,
     {
         [ARG_0] = {"ctx_id", 4},
         [ARG_1] = {"iocb", 4},
         [ARG_2] = {"result", 4},
     }},
    {"fadvise64",
     246,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"offset", 8},
         [ARG_2] = {"len", 4},
         [ARG_3] = {"advice", 4},
     }},
    {"exit_group",
     247,
     {
         [ARG_0] = {"error_code", 4},
     }},
    {"epoll_create",
     249,
     {
         [ARG_0] = {"size", 4},
     }},
    {"epoll_ctl",
     250,
     {
         [ARG_0] = {"epfd", 4},
         [ARG_1] = {"op", 4},
         [ARG_2] = {"fd", 4},
         [ARG_3] = {"event", 4},
     }},
    {"epoll_wait",
     251,
     {
         [ARG_0] = {"epfd", 4},
         [ARG_1] = {"events", 4},
         [ARG_2] = {"maxevents", 4},
         [ARG_3] = {"timeout", 4},
     }},
    {"remap_file_pages",
     252,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"size", 4},
         [ARG_2] = {"prot", 4},
         [ARG_3] = {"pgoff", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"set_tid_address",
     253,
     {
         [ARG_0] = {"tidptr", 4},
     }},
    {"timer_create",
     254,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"timer_event_spec", 4},
         [ARG_2] = {"created_timer_id", 4},
     }},
    {"timer_settime",
     255,
     {
         [ARG_0] = {"timer_id", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"new_setting", 4},
         [ARG_3] = {"old_setting", 4},
     }},
    {"timer_gettime",
     256,
     {
         [ARG_0] = {"timer_id", 4},
         [ARG_1] = {"setting", 4},
     }},
    {"timer_getoverrun",
     257,
     {
         [ARG_0] = {"timer_id", 4},
     }},
    {"timer_delete",
     258,
     {
         [ARG_0] = {"timer_id", 4},
     }},
    {"clock_settime",
     259,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"tp", 4},
     }},
    {"clock_gettime",
     260,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"tp", 4},
     }},
    {"clock_getres",
     261,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"tp", 4},
     }},
    {"clock_nanosleep",
     262,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"rqtp", 4},
         [ARG_3] = {"rmtp", 4},
     }},
    {"statfs64",
     263,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"sz", 4},
         [ARG_2] = {"buf", 4},
     }},
    {"fstatfs64",
     264,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"sz", 4},
         [ARG_2] = {"buf", 4},
     }},
    {"tgkill",
     265,
     {
         [ARG_0] = {"tgid", 4},
         [ARG_1] = {"pid", 4},
         [ARG_2] = {"sig", 4},
     }},
    {"utimes",
     266,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"utimes", 4},
     }},
    {"fadvise64_64",
     267,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"offset", 8},
         [ARG_2] = {"len", 8},
         [ARG_3] = {"advice", 4},
     }},
    {"mbind",
     268,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"mode", 4},
         [ARG_3] = {"nmask", 4},
         [ARG_4] = {"maxnode", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"get_mempolicy",
     269,
     {
         [ARG_0] = {"policy", 4},
         [ARG_1] = {"nmask", 4},
         [ARG_2] = {"maxnode", 4},
         [ARG_3] = {"addr", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"set_mempolicy",
     270,
     {
         [ARG_0] = {"mode", 4},
         [ARG_1] = {"nmask", 4},
         [ARG_2] = {"maxnode", 4},
     }},
    {"mq_open",
     271,
     {
         [ARG_0] = {"u_name", 4},
         [ARG_1] = {"oflag", 4},
         [ARG_2] = {"mode", 2},
         [ARG_3] = {"u_attr", 4},
     }},
    {"mq_unlink",
     272,
     {
         [ARG_0] = {"u_name", 4},
     }},
    {"mq_timedsend",
     273,
     {
         [ARG_0] = {"mqdes", 4},
         [ARG_1] = {"u_msg_ptr", 4},
         [ARG_2] = {"msg_len", 4},
         [ARG_3] = {"msg_prio", 4},
         [ARG_4] = {"u_abs_timeout", 4},
     }},
    {"mq_timedreceive",
     274,
     {
         [ARG_0] = {"mqdes", 4},
         [ARG_1] = {"u_msg_ptr", 4},
         [ARG_2] = {"msg_len", 4},
         [ARG_3] = {"u_msg_prio", 4},
         [ARG_4] = {"u_abs_timeout", 4},
     }},
    {"mq_notify",
     275,
     {
         [ARG_0] = {"mqdes", 4},
         [ARG_1] = {"u_notification", 4},
     }},
    {"mq_getsetattr",
     276,
     {
         [ARG_0] = {"mqdes", 4},
         [ARG_1] = {"u_mqstat", 4},
         [ARG_2] = {"u_omqstat", 4},
     }},
    {"waitid",
     277,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"upid", 4},
         [ARG_2] = {"infop", 4},
         [ARG_3] = {"options", 4},
         [ARG_4] = {"ru", 4},
     }},
    {"add_key",
     279,
     {
         [ARG_0] = {"_type", 4},
         [ARG_1] = {"_description", 4},
         [ARG_2] = {"_payload", 4},
         [ARG_3] = {"plen", 4},
         [ARG_4] = {"ringid", 4},
     }},
    {"request_key",
     280,
     {
         [ARG_0] = {"_type", 4},
         [ARG_1] = {"_description", 4},
         [ARG_2] = {"_callout_info", 4},
         [ARG_3] = {"destringid", 4},
     }},
    {"keyctl",
     281,
     {
         [ARG_0] = {"option", 4},
         [ARG_1] = {"arg2", 4},
         [ARG_2] = {"arg3", 4},
         [ARG_3] = {"arg4", 4},
         [ARG_4] = {"arg5", 4},
     }},
    {"ioprio_set",
     282,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"who", 4},
         [ARG_2] = {"ioprio", 4},
     }},
    {"ioprio_get",
     283,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"who", 4},
     }},
    {"inotify_init", 284, {}},
    {"inotify_add_watch",
     285,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"mask", 4},
     }},
    {"inotify_rm_watch",
     286,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"wd", 4},
     }},
    {"migrate_pages",
     287,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"maxnode", 4},
         [ARG_2] = {"old_nodes", 4},
         [ARG_3] = {"new_nodes", 4},
     }},
    {"openat",
     288,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"flags", 4},
         [ARG_3] = {"mode", 2},
     }},
    {"mkdirat",
     289,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"mode", 2},
     }},
    {"mknodat",
     290,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"mode", 2},
         [ARG_3] = {"dev", 4},
     }},
    {"fchownat",
     291,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"user", 4},
         [ARG_3] = {"group", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"futimesat",
     292,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"utimes", 4},
     }},
    {"fstatat64",
     293,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"statbuf", 4},
         [ARG_3] = {"flag", 4},
     }},
    {"unlinkat",
     294,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"renameat",
     295,
     {
         [ARG_0] = {"olddfd", 4},
         [ARG_1] = {"oldname", 4},
         [ARG_2] = {"newdfd", 4},
         [ARG_3] = {"newname", 4},
     }},
    {"linkat",
     296,
     {
         [ARG_0] = {"olddfd", 4},
         [ARG_1] = {"oldname", 4},
         [ARG_2] = {"newdfd", 4},
         [ARG_3] = {"newname", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"symlinkat",
     297,
     {
         [ARG_0] = {"oldname", 4},
         [ARG_1] = {"newdfd", 4},
         [ARG_2] = {"newname", 4},
     }},
    {"readlinkat",
     298,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"buf", 4},
         [ARG_3] = {"bufsiz", 4},
     }},
    {"fchmodat",
     299,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"mode", 2},
     }},
    {"faccessat",
     300,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"mode", 4},
     }},
    {"pselect6",
     301,
     {
         [ARG_0] = {"n", 4},
         [ARG_1] = {"inp", 4},
         [ARG_2] = {"outp", 4},
         [ARG_3] = {"exp", 4},
         [ARG_4] = {"tsp", 4},
         [ARG_5] = {"sig", 4},
     }},
    {"ppoll",
     302,
     {
         [ARG_0] = {"ufds", 4},
         [ARG_1] = {"nfds", 4},
         [ARG_2] = {"tsp", 4},
         [ARG_3] = {"sigmask", 4},
         [ARG_4] = {"sigsetsize", 4},
     }},
    {"unshare",
     303,
     {
         [ARG_0] = {"unshare_flags", 4},
     }},
    {"set_robust_list",
     304,
     {
         [ARG_0] = {"head", 4},
         [ARG_1] = {"len", 4},
     }},
    {"get_robust_list",
     305,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"head_ptr", 4},
         [ARG_2] = {"len_ptr", 4},
     }},
    {"splice",
     306,
     {
         [ARG_0] = {"fd_in", 4},
         [ARG_1] = {"off_in", 4},
         [ARG_2] = {"fd_out", 4},
         [ARG_3] = {"off_out", 4},
         [ARG_4] = {"len", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"sync_file_range",
     307,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"offset", 8},
         [ARG_2] = {"nbytes", 8},
         [ARG_3] = {"flags", 4},
     }},
    {"tee",
     308,
     {
         [ARG_0] = {"fdin", 4},
         [ARG_1] = {"fdout", 4},
         [ARG_2] = {"len", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"vmsplice",
     309,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"iov", 4},
         [ARG_2] = {"nr_segs", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"move_pages",
     310,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"nr_pages", 4},
         [ARG_2] = {"pages", 4},
         [ARG_3] = {"nodes", 4},
         [ARG_4] = {"status", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"sched_setaffinity",
     311,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"user_mask_ptr", 4},
     }},
    {"sched_getaffinity",
     312,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"user_mask_ptr", 4},
     }},
    {"kexec_load",
     313,
     {
         [ARG_0] = {"entry", 4},
         [ARG_1] = {"nr_segments", 4},
         [ARG_2] = {"segments", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"getcpu",
     314,
     {
         [ARG_0] = {"cpup", 4},
         [ARG_1] = {"nodep", 4},
         [ARG_2] = {"unused", 4},
     }},
    {"epoll_pwait",
     315,
     {
         [ARG_0] = {"epfd", 4},
         [ARG_1] = {"events", 4},
         [ARG_2] = {"maxevents", 4},
         [ARG_3] = {"timeout", 4},
         [ARG_4] = {"sigmask", 4},
         [ARG_5] = {"sigsetsize", 4},
     }},
    {"utimensat",
     316,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"utimes", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"signalfd",
     317,
     {
         [ARG_0] = {"ufd", 4},
         [ARG_1] = {"user_mask", 4},
         [ARG_2] = {"sizemask", 4},
     }},
    {"timerfd_create",
     318,
     {
         [ARG_0] = {"clockid", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"eventfd",
     319,
     {
         [ARG_0] = {"count", 4},
     }},
    {"fallocate",
     320,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"mode", 4},
         [ARG_2] = {"offset", 8},
         [ARG_3] = {"len", 8},
     }},
    {"timerfd_settime",
     321,
     {
         [ARG_0] = {"ufd", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"utmr", 4},
         [ARG_3] = {"otmr", 4},
     }},
    {"timerfd_gettime",
     322,
     {
         [ARG_0] = {"ufd", 4},
         [ARG_1] = {"otmr", 4},
     }},
    {"signalfd4",
     323,
     {
         [ARG_0] = {"ufd", 4},
         [ARG_1] = {"user_mask", 4},
         [ARG_2] = {"sizemask", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"eventfd2",
     324,
     {
         [ARG_0] = {"count", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"epoll_create1",
     325,
     {
         [ARG_0] = {"flags", 4},
     }},
    {"dup3",
     326,
     {
         [ARG_0] = {"oldfd", 4},
         [ARG_1] = {"newfd", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"pipe2",
     327,
     {
         [ARG_0] = {"fildes", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"inotify_init1",
     328,
     {
         [ARG_0] = {"flags", 4},
     }},
    {"preadv",
     329,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"pos_l", 4},
         [ARG_4] = {"pos_h", 4},
     }},
    {"pwritev",
     330,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"pos_l", 4},
         [ARG_4] = {"pos_h", 4},
     }},
    {"rt_tgsigqueueinfo",
     331,
     {
         [ARG_0] = {"tgid", 4},
         [ARG_1] = {"pid", 4},
         [ARG_2] = {"sig", 4},
         [ARG_3] = {"uinfo", 4},
     }},
    {"perf_event_open",
     332,
     {
         [ARG_0] = {"attr_uptr", 4},
         [ARG_1] = {"pid", 4},
         [ARG_2] = {"cpu", 4},
         [ARG_3] = {"group_fd", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"get_thread_area",
     333,
     {
         [ARG_0] = {"u_info", 4},
     }},
    {"set_thread_area",
     334,
     {
         [ARG_0] = {"u_info", 4},
     }},
    {"atomic_cmpxchg_32",
     335,
     {
         [ARG_0] = {"mem", 4},
         [ARG_1] = {"oldval", 4},
         [ARG_2] = {"newval", 4},
     }},
    {"atomic_barrier", 336, {}},
    {"fanotify_init",
     337,
     {
         [ARG_0] = {"flags", 4},
         [ARG_1] = {"event_f_flags", 4},
     }},
    {"fanotify_mark",
     338,
     {
         [ARG_0] = {"fanotify_fd", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"mask", 8},
         [ARG_3] = {"dfd", 4},
         [ARG_4] = {"pathname", 4},
     }},
    {"prlimit64",
     339,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"resource", 4},
         [ARG_2] = {"new_rlim", 4},
         [ARG_3] = {"old_rlim", 4},
     }},
    {"name_to_handle_at",
     340,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"handle", 4},
         [ARG_3] = {"mnt_id", 4},
         [ARG_4] = {"flag", 4},
     }},
    {"open_by_handle_at",
     341,
     {
         [ARG_0] = {"mountdirfd", 4},
         [ARG_1] = {"handle", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"clock_adjtime",
     342,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"utx", 4},
     }},
    {"syncfs",
     343,
     {
         [ARG_0] = {"fd", 4},
     }},
    {"setns",
     344,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"nstype", 4},
     }},
    {"process_vm_readv",
     345,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"lvec", 4},
         [ARG_2] = {"liovcnt", 4},
         [ARG_3] = {"rvec", 4},
         [ARG_4] = {"riovcnt", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"process_vm_writev",
     346,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"lvec", 4},
         [ARG_2] = {"liovcnt", 4},
         [ARG_3] = {"rvec", 4},
         [ARG_4] = {"riovcnt", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"kcmp",
     347,
     {
         [ARG_0] = {"pid1", 4},
         [ARG_1] = {"pid2", 4},
         [ARG_2] = {"type", 4},
         [ARG_3] = {"idx1", 4},
         [ARG_4] = {"idx2", 4},
     }},
    {"finit_module",
     348,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"uargs", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"sched_setattr",
     349,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"uattr", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"sched_getattr",
     350,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"uattr", 4},
         [ARG_2] = {"size", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"renameat2",
     351,
     {
         [ARG_0] = {"olddfd", 4},
         [ARG_1] = {"oldname", 4},
         [ARG_2] = {"newdfd", 4},
         [ARG_3] = {"newname", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"getrandom",
     352,
     {
         [ARG_0] = {"buf", 4},
         [ARG_1] = {"count", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"memfd_create",
     353,
     {
         [ARG_0] = {"uname", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"bpf",
     354,
     {
         [ARG_0] = {"cmd", 4},
         [ARG_1] = {"uattr", 4},
         [ARG_2] = {"size", 4},
     }},
    {"execveat",
     355,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"argv", 4},
         [ARG_3] = {"envp", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"socket",
     356,
     {
         [ARG_0] = {"family", 4},
         [ARG_1] = {"type", 4},
         [ARG_2] = {"protocol", 4},
     }},
    {"socketpair",
     357,
     {
         [ARG_0] = {"family", 4},
         [ARG_1] = {"type", 4},
         [ARG_2] = {"protocol", 4},
         [ARG_3] = {"usockvec", 4},
     }},
    {"bind",
     358,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"umyaddr", 4},
         [ARG_2] = {"addrlen", 4},
     }},
    {"connect",
     359,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"uservaddr", 4},
         [ARG_2] = {"addrlen", 4},
     }},
    {"listen",
     360,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"backlog", 4},
     }},
    {"accept4",
     361,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"upeer_sockaddr", 4},
         [ARG_2] = {"upeer_addrlen", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"getsockopt",
     362,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"level", 4},
         [ARG_2] = {"optname", 4},
         [ARG_3] = {"optval", 4},
         [ARG_4] = {"optlen", 4},
     }},
    {"setsockopt",
     363,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"level", 4},
         [ARG_2] = {"optname", 4},
         [ARG_3] = {"optval", 4},
         [ARG_4] = {"optlen", 4},
     }},
    {"getsockname",
     364,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"usockaddr", 4},
         [ARG_2] = {"usockaddr_len", 4},
     }},
    {"getpeername",
     365,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"usockaddr", 4},
         [ARG_2] = {"usockaddr_len", 4},
     }},
    {"sendto",
     366,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buff", 4},
         [ARG_2] = {"len", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"addr", 4},
         [ARG_5] = {"addr_len", 4},
     }},
    {"sendmsg",
     367,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"msg", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"recvfrom",
     368,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"ubuf", 4},
         [ARG_2] = {"size", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"addr", 4},
         [ARG_5] = {"addr_len", 4},
     }},
    {"recvmsg",
     369,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"msg", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"shutdown",
     370,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"how", 4},
     }},
    {"recvmmsg",
     371,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"mmsg", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"timeout", 4},
     }},
    {"sendmmsg",
     372,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"mmsg", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"userfaultfd",
     373,
     {
         [ARG_0] = {"flags", 4},
     }},
    {"membarrier",
     374,
     {
         [ARG_0] = {"cmd", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"mlock2",
     375,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"copy_file_range",
     376,
     {
         [ARG_0] = {"fd_in", 4},
         [ARG_1] = {"off_in", 4},
         [ARG_2] = {"fd_out", 4},
         [ARG_3] = {"off_out", 4},
         [ARG_4] = {"len", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"preadv2",
     377,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"pos_l", 4},
         [ARG_4] = {"pos_h", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"pwritev2",
     378,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"pos_l", 4},
         [ARG_4] = {"pos_h", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"statx",
     379,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"flags", 4},
         [ARG_3] = {"mask", 4},
         [ARG_4] = {"statxbuf", 4},
     }},
    {"seccomp",
     380,
     {
         [ARG_0] = {"op", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"uargs", 4},
     }},
    {"pkey_mprotect",
     381,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"prot", 4},
         [ARG_3] = {"pkey", 4},
     }},
    {"pkey_alloc",
     382,
     {
         [ARG_0] = {"flags", 4},
         [ARG_1] = {"init_val", 4},
     }},
    {"pkey_free",
     383,
     {
         [ARG_0] = {"pkey", 4},
     }},
    {"rseq",
     384,
     {
         [ARG_0] = {"rseq", 4},
         [ARG_1] = {"rseq_len", 4},
         [ARG_2] = {"flags", 4},
         [ARG_3] = {"sig", 4},
     }},
    {"semget",
     393,
     {
         [ARG_0] = {"key", 4},
         [ARG_1] = {"nsems", 4},
         [ARG_2] = {"semflg", 4},
     }},
    {"semctl",
     394,
     {
         [ARG_0] = {"semid", 4},
         [ARG_1] = {"semnum", 4},
         [ARG_2] = {"cmd", 4},
         [ARG_3] = {"arg", 4},
     }},
    {"shmget",
     395,
     {
         [ARG_0] = {"key", 4},
         [ARG_1] = {"size", 4},
         [ARG_2] = {"shmflg", 4},
     }},
    {"shmctl",
     396,
     {
         [ARG_0] = {"shmid", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"buf", 4},
     }},
    {"shmat",
     397,
     {
         [ARG_0] = {"shmid", 4},
         [ARG_1] = {"shmaddr", 4},
         [ARG_2] = {"shmflg", 4},
     }},
    {"shmdt",
     398,
     {
         [ARG_0] = {"shmaddr", 4},
     }},
    {"msgget",
     399,
     {
         [ARG_0] = {"key", 4},
         [ARG_1] = {"msgflg", 4},
     }},
    {"msgsnd",
     400,
     {
         [ARG_0] = {"msqid", 4},
         [ARG_1] = {"msgp", 4},
         [ARG_2] = {"msgsz", 4},
         [ARG_3] = {"msgflg", 4},
     }},
    {"msgrcv",
     401,
     {
         [ARG_0] = {"msqid", 4},
         [ARG_1] = {"msgp", 4},
         [ARG_2] = {"msgsz", 4},
         [ARG_3] = {"msgtyp", 4},
         [ARG_4] = {"msgflg", 4},
     }},
    {"msgctl",
     402,
     {
         [ARG_0] = {"msqid", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"buf", 4},
     }},
    {"clock_gettime64",
     403,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"tp", 4},
     }},
    {"clock_settime64",
     404,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"tp", 4},
     }},
    {"clock_adjtime64",
     405,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"utx", 4},
     }},
    {"clock_getres_time64",
     406,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"tp", 4},
     }},
    {"clock_nanosleep_time64",
     407,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"rqtp", 4},
         [ARG_3] = {"rmtp", 4},
     }},
    {"timer_gettime64",
     408,
     {
         [ARG_0] = {"timer_id", 4},
         [ARG_1] = {"setting", 4},
     }},
    {"timer_settime64",
     409,
     {
         [ARG_0] = {"timer_id", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"new_setting", 4},
         [ARG_3] = {"old_setting", 4},
     }},
    {"timerfd_gettime64",
     410,
     {
         [ARG_0] = {"ufd", 4},
         [ARG_1] = {"otmr", 4},
     }},
    {"timerfd_settime64",
     411,
     {
         [ARG_0] = {"ufd", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"utmr", 4},
         [ARG_3] = {"otmr", 4},
     }},
    {"utimensat_time64",
     412,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"utimes", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"pselect6_time64",
     413,
     {
         [ARG_0] = {"n", 4},
         [ARG_1] = {"inp", 4},
         [ARG_2] = {"outp", 4},
         [ARG_3] = {"exp", 4},
         [ARG_4] = {"tsp", 4},
         [ARG_5] = {"sig", 4},
     }},
    {"ppoll_time64",
     414,
     {
         [ARG_0] = {"ufds", 4},
         [ARG_1] = {"nfds", 4},
         [ARG_2] = {"tsp", 4},
         [ARG_3] = {"sigmask", 4},
         [ARG_4] = {"sigsetsize", 4},
     }},
    {"io_pgetevents_time64",
     416,
     {
         [ARG_0] = {"ctx_id", 4},
         [ARG_1] = {"min_nr", 4},
         [ARG_2] = {"nr", 4},
         [ARG_3] = {"events", 4},
         [ARG_4] = {"timeout", 4},
         [ARG_5] = {"usig", 4},
     }},
    {"recvmmsg_time64",
     417,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"mmsg", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"timeout", 4},
     }},
    {"mq_timedsend_time64",
     418,
     {
         [ARG_0] = {"mqdes", 4},
         [ARG_1] = {"u_msg_ptr", 4},
         [ARG_2] = {"msg_len", 4},
         [ARG_3] = {"msg_prio", 4},
         [ARG_4] = {"u_abs_timeout", 4},
     }},
    {"mq_timedreceive_time64",
     419,
     {
         [ARG_0] = {"mqdes", 4},
         [ARG_1] = {"u_msg_ptr", 4},
         [ARG_2] = {"msg_len", 4},
         [ARG_3] = {"u_msg_prio", 4},
         [ARG_4] = {"u_abs_timeout", 4},
     }},
    {"semtimedop_time64",
     420,
     {
         [ARG_0] = {"semid", 4},
         [ARG_1] = {"tsops", 4},
         [ARG_2] = {"nsops", 4},
         [ARG_3] = {"timeout", 4},
     }},
    {"rt_sigtimedwait_time64",
     421,
     {
         [ARG_0] = {"uthese", 4},
         [ARG_1] = {"uinfo", 4},
         [ARG_2] = {"uts", 4},
         [ARG_3] = {"sigsetsize", 4},
     }},
    {"futex_time64",
     422,
     {
         [ARG_0] = {"uaddr", 4},
         [ARG_1] = {"op", 4},
         [ARG_2] = {"val", 4},
         [ARG_3] = {"utime", 4},
         [ARG_4] = {"uaddr2", 4},
         [ARG_5] = {"val3", 4},
     }},
    {"sched_rr_get_interval_time64",
     423,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"interval", 4},
     }},
    {"pidfd_send_signal",
     424,
     {
         [ARG_0] = {"pidfd", 4},
         [ARG_1] = {"sig", 4},
         [ARG_2] = {"info", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"io_uring_setup",
     425,
     {
         [ARG_0] = {"entries", 4},
         [ARG_1] = {"params", 4},
     }},
    {"io_uring_enter",
     426,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"to_submit", 4},
         [ARG_2] = {"min_complete", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"argp", 4},
         [ARG_5] = {"argsz", 4},
     }},
    {"io_uring_register",
     427,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"opcode", 4},
         [ARG_2] = {"arg", 4},
         [ARG_3] = {"nr_args", 4},
     }},
    {"open_tree",
     428,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"move_mount",
     429,
     {
         [ARG_0] = {"from_dfd", 4},
         [ARG_1] = {"from_pathname", 4},
         [ARG_2] = {"to_dfd", 4},
         [ARG_3] = {"to_pathname", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"fsopen",
     430,
     {
         [ARG_0] = {"_fs_name", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"fsconfig",
     431,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"_key", 4},
         [ARG_3] = {"_value", 4},
         [ARG_4] = {"aux", 4},
     }},
    {"fsmount",
     432,
     {
         [ARG_0] = {"fs_fd", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"attr_flags", 4},
     }},
    {"fspick",
     433,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"path", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"pidfd_open",
     434,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"clone3",
     435,
     {
         [ARG_0] = {"uargs", 4},
         [ARG_1] = {"size", 4},
     }},
    {"close_range",
     436,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"max_fd", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"openat2",
     437,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"how", 4},
         [ARG_3] = {"size", 4},
     }},
    {"pidfd_getfd",
     438,
     {
         [ARG_0] = {"pidfd", 4},
         [ARG_1] = {"fd", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"faccessat2",
     439,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"mode", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"process_madvise",
     440,
     {
         [ARG_0] = {"pidfd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"behavior", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"epoll_pwait2",
     441,
     {
         [ARG_0] = {"epfd", 4},
         [ARG_1] = {"events", 4},
         [ARG_2] = {"maxevents", 4},
         [ARG_3] = {"timeout", 4},
         [ARG_4] = {"sigmask", 4},
         [ARG_5] = {"sigsetsize", 4},
     }},
    {"mount_setattr",
     442,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"path", 4},
         [ARG_2] = {"flags", 4},
         [ARG_3] = {"uattr", 4},
         [ARG_4] = {"usize", 4},
     }},
    {"quotactl_fd",
     443,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"id", 4},
         [ARG_3] = {"addr", 4},
     }},
    {"landlock_create_ruleset",
     444,
     {
         [ARG_0] = {"attr", 4},
         [ARG_1] = {"size", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"landlock_add_rule",
     445,
     {
         [ARG_0] = {"ruleset_fd", 4},
         [ARG_1] = {"rule_type", 4},
         [ARG_2] = {"rule_attr", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"landlock_restrict_self",
     446,
     {
         [ARG_0] = {"ruleset_fd", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"process_mrelease",
     448,
     {
         [ARG_0] = {"pidfd", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"futex_waitv",
     449,
     {
         [ARG_0] = {"waiters", 4},
         [ARG_1] = {"nr_futexes", 4},
         [ARG_2] = {"flags", 4},
         [ARG_3] = {"timeout", 4},
         [ARG_4] = {"clockid", 4},
     }},
    {"set_mempolicy_home_node",
     450,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"home_node", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"cachestat",
     451,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"cstat_range", 4},
         [ARG_2] = {"cstat", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"fchmodat2",
     452,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"mode", 2},
         [ARG_3] = {"flags", 4},
     }},
    {"map_shadow_stack",
     453,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"size", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"futex_wake",
     454,
     {
         [ARG_0] = {"uaddr", 4},
         [ARG_1] = {"nr_wake", 4},
         [ARG_2] = {"flags_or_mask", 4},
     }},
    {"futex_wait",
     455,
     {
         [ARG_0] = {"uaddr", 4},
         [ARG_1] = {"val", 4},
         [ARG_2] = {"flags", 4},
         [ARG_3] = {"timeout", 4},
     }},
    {"futex_requeue",
     456,
     {
         [ARG_0] = {"uaddr", 4},
         [ARG_1] = {"nr_wake", 4},
         [ARG_2] = {"nr_requeue", 4},
         [ARG_3] = {"uaddr2", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"statmount",
     457,
     {
         [ARG_0] = {"req", 4},
         [ARG_1] = {"reqlen", 4},
         [ARG_2] = {"smbuf", 4},
         [ARG_3] = {"buflen", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"listmount",
     458,
     {
         [ARG_0] = {"req", 4},
         [ARG_1] = {"reqlen", 4},
         [ARG_2] = {"buf", 4},
         [ARG_3] = {"bufsize", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"lsm_get_self_attr",
     459,
     {
         [ARG_0] = {"attr", 4},
         [ARG_1] = {"ctx", 4},
         [ARG_2] = {"size_ptr", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"lsm_set_self_attr",
     460,
     {
         [ARG_0] = {"attr", 4},
         [ARG_1] = {"ctx", 4},
         [ARG_2] = {"size", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"lsm_list_modules",
     461,
     {
         [ARG_0] = {"ids", 4},
         [ARG_1] = {"size_ptr", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"mseal",
     462,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"size", 4},
         [ARG_2] = {"size", 4},
     }},
    {"setxattrat",
     463,
     {
         [ARG_0] = {"dirfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"name", 4},
         [ARG_3] = {"value", 4},
         [ARG_4] = {"size", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"getxattrat",
     464,
     {
         [ARG_0] = {"dirfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"name", 4},
         [ARG_3] = {"value", 4},
         [ARG_4] = {"size", 4},
     }},
    {"listxattrat",
     465,
     {
         [ARG_0] = {"dirfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"list", 4},
         [ARG_3] = {"size", 4},
     }},
    {"removexattrat",
     466,
     {
         [ARG_0] = {"dirfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"name", 4},
     }},
    {"open_tree_attr",
     467,
     {
         [ARG_0] = {"dirfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"flags", 4},
         [ARG_3] = {"attr", 4},
         [ARG_4] = {"size", 4},
     }},
    {"file_getattr",
     468,
     {
         [ARG_0] = {"dirfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"fileattr", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"file_setattr",
     469,
     {
         [ARG_0] = {"dirfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"fileattr", 4},
         [ARG_3] = {"flags", 4},
     }},
};

const size_t m68k_syscall_list_size =
    sizeof(m68k_syscall_list) / sizeof(m68k_syscall_list[0]);
