/*
   Kafel - syscalls (mipso32)
   -----------------------------------------

   Copyright 2016 Google Inc. All Rights Reserved.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

*/

#include <stddef.h>

#include "../syscall.h"

#define ARG_0 0
#define ARG_1 1
#define ARG_2 2
#define ARG_3 3
#define ARG_4 4
#define ARG_5 5

#define NORMAL false

const struct syscall_descriptor mipso32_syscall_list[] = {
    {"accept",
     168,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"upeer_sockaddr", 4},
         [ARG_2] = {"upeer_addrlen", 4},
     }},
    {"accept4",
     334,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"upeer_sockaddr", 4},
         [ARG_2] = {"upeer_addrlen", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"access",
     33,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"mode", 4},
     }},
    {"acct",
     51,
     NORMAL,
     {
         [ARG_0] = {"name", 4},
     }},
    {"add_key",
     280,
     NORMAL,
     {
         [ARG_0] = {"_type", 4},
         [ARG_1] = {"_description", 4},
         [ARG_2] = {"_payload", 4},
         [ARG_3] = {"plen", 4},
         [ARG_4] = {"ringid", 4},
     }},
    {"adjtimex",
     4124,
     NORMAL,
     {
         [ARG_0] = {"txc_p", 4},
     }},
    {"adjtimex_time32",
     124,
     NORMAL,
     {
         [ARG_0] = {"utp", 4},
     }},
    {"alarm",
     27,
     NORMAL,
     {
         [ARG_0] = {"seconds", 4},
     }},
    {"bdflush",
     134,
     NORMAL,
     {
         [ARG_0] = {"func", 4},
         [ARG_1] = {"data", 4},
     }},
    {"bind",
     169,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"umyaddr", 4},
         [ARG_2] = {"addrlen", 4},
     }},
    {"bpf",
     355,
     NORMAL,
     {
         [ARG_0] = {"cmd", 4},
         [ARG_1] = {"uattr", 4},
         [ARG_2] = {"size", 4},
     }},
    {"breakpoint", 983041, NORMAL, {}},
    {"brk",
     45,
     NORMAL,
     {
         [ARG_0] = {"brk", 4},
     }},
    {"cachectl",
     148,
     NORMAL,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"nbytes", 4},
         [ARG_2] = {"op", 4},
     }},
    {"cacheflush",
     147,
     NORMAL,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"bytes", 4},
         [ARG_2] = {"cache", 4},
     }},
    {"capget",
     204,
     NORMAL,
     {
         [ARG_0] = {"header", 4},
         [ARG_1] = {"dataptr", 4},
     }},
    {"capset",
     205,
     NORMAL,
     {
         [ARG_0] = {"header", 4},
         [ARG_1] = {"data", 4},
     }},
    {"chdir",
     12,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
     }},
    {"chmod",
     15,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"mode", 2},
     }},
    {"chown",
     202,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"user", 4},
         [ARG_2] = {"group", 4},
     }},
    {"chroot",
     61,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
     }},
    {"clock_adjtime",
     405,
     NORMAL,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"utx", 4},
     }},
    {"clock_adjtime32",
     341,
     NORMAL,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"utp", 4},
     }},
    {"clock_getres",
     406,
     NORMAL,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"tp", 4},
     }},
    {"clock_getres_time32",
     264,
     NORMAL,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"tp", 4},
     }},
    {"clock_gettime",
     403,
     NORMAL,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"tp", 4},
     }},
    {"clock_gettime32",
     263,
     NORMAL,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"tp", 4},
     }},
    {"clock_nanosleep",
     407,
     NORMAL,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"rqtp", 4},
         [ARG_3] = {"rmtp", 4},
     }},
    {"clock_nanosleep_time32",
     265,
     NORMAL,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"rqtp", 4},
         [ARG_3] = {"rmtp", 4},
     }},
    {"clock_settime",
     404,
     NORMAL,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"tp", 4},
     }},
    {"clock_settime32",
     262,
     NORMAL,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"tp", 4},
     }},
    {"clone",
     120,
     NORMAL,
     {
         [ARG_0] = {"clone_flags", 4},
         [ARG_1] = {"newsp", 4},
         [ARG_2] = {"parent_tidptr", 4},
         [ARG_3] = {"tls", 4},
         [ARG_4] = {"child_tidptr", 4},
     }},
    {"clone3",
     435,
     NORMAL,
     {
         [ARG_0] = {"uargs", 4},
         [ARG_1] = {"size", 4},
     }},
    {"close",
     6,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
     }},
    {"connect",
     170,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"uservaddr", 4},
         [ARG_2] = {"addrlen", 4},
     }},
    {"copy_file_range",
     360,
     NORMAL,
     {
         [ARG_0] = {"fd_in", 4},
         [ARG_1] = {"off_in", 4},
         [ARG_2] = {"fd_out", 4},
         [ARG_3] = {"off_out", 4},
         [ARG_4] = {"len", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"creat",
     8,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"mode", 2},
     }},
    {"delete_module",
     129,
     NORMAL,
     {
         [ARG_0] = {"name_user", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"dup",
     41,
     NORMAL,
     {
         [ARG_0] = {"fildes", 4},
     }},
    {"dup2",
     63,
     NORMAL,
     {
         [ARG_0] = {"oldfd", 4},
         [ARG_1] = {"newfd", 4},
     }},
    {"dup3",
     327,
     NORMAL,
     {
         [ARG_0] = {"oldfd", 4},
         [ARG_1] = {"newfd", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"epoll_create",
     248,
     NORMAL,
     {
         [ARG_0] = {"size", 4},
     }},
    {"epoll_create1",
     326,
     NORMAL,
     {
         [ARG_0] = {"flags", 4},
     }},
    {"epoll_ctl",
     249,
     NORMAL,
     {
         [ARG_0] = {"epfd", 4},
         [ARG_1] = {"op", 4},
         [ARG_2] = {"fd", 4},
         [ARG_3] = {"event", 4},
     }},
    {"epoll_pwait",
     313,
     NORMAL,
     {
         [ARG_0] = {"epfd", 4},
         [ARG_1] = {"events", 4},
         [ARG_2] = {"maxevents", 4},
         [ARG_3] = {"timeout", 4},
         [ARG_4] = {"sigmask", 4},
         [ARG_5] = {"sigsetsize", 4},
     }},
    {"epoll_wait",
     250,
     NORMAL,
     {
         [ARG_0] = {"epfd", 4},
         [ARG_1] = {"events", 4},
         [ARG_2] = {"maxevents", 4},
         [ARG_3] = {"timeout", 4},
     }},
    {"eventfd",
     319,
     NORMAL,
     {
         [ARG_0] = {"count", 4},
     }},
    {"eventfd2",
     325,
     NORMAL,
     {
         [ARG_0] = {"count", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"execve",
     11,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"argv", 4},
         [ARG_2] = {"envp", 4},
     }},
    {"execveat",
     356,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"argv", 4},
         [ARG_3] = {"envp", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"exit",
     1,
     NORMAL,
     {
         [ARG_0] = {"error_code", 4},
     }},
    {"exit_group",
     246,
     NORMAL,
     {
         [ARG_0] = {"error_code", 4},
     }},
    {"faccessat",
     300,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"mode", 4},
     }},
    {"faccessat2",
     439,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"mode", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"fadvise64_64",
     254,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"offset", 8},
         [ARG_2] = {"len", 8},
         [ARG_3] = {"advice", 4},
     }},
    {"fallocate",
     320,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"mode", 4},
         [ARG_2] = {"offset", 8},
         [ARG_3] = {"len", 8},
     }},
    {"fanotify_init",
     336,
     NORMAL,
     {
         [ARG_0] = {"flags", 4},
         [ARG_1] = {"event_f_flags", 4},
     }},
    {"fanotify_mark",
     337,
     NORMAL,
     {
         [ARG_0] = {"fanotify_fd", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"mask", 8},
         [ARG_3] = {"dfd", 4},
         [ARG_4] = {"pathname", 4},
     }},
    {"fchdir",
     133,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
     }},
    {"fchmod",
     94,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"mode", 2},
     }},
    {"fchmodat",
     299,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"mode", 2},
     }},
    {"fchown",
     95,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"user", 4},
         [ARG_2] = {"group", 4},
     }},
    {"fchownat",
     291,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"user", 4},
         [ARG_3] = {"group", 4},
         [ARG_4] = {"flag", 4},
     }},
    {"fcntl",
     55,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"arg", 4},
     }},
    {"fcntl64",
     220,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"arg", 4},
     }},
    {"fdatasync",
     152,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
     }},
    {"fgetxattr",
     229,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"value", 4},
         [ARG_3] = {"size", 4},
     }},
    {"finit_module",
     348,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"uargs", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"flistxattr",
     232,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"list", 4},
         [ARG_2] = {"size", 4},
     }},
    {"flock",
     143,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"cmd", 4},
     }},
    {"fork", 2, NORMAL, {}},
    {"fremovexattr",
     235,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"name", 4},
     }},
    {"fsconfig",
     431,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"_key", 4},
         [ARG_3] = {"_value", 4},
         [ARG_4] = {"aux", 4},
     }},
    {"fsetxattr",
     226,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"value", 4},
         [ARG_3] = {"size", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"fsmount",
     432,
     NORMAL,
     {
         [ARG_0] = {"fs_fd", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"attr_flags", 4},
     }},
    {"fsopen",
     430,
     NORMAL,
     {
         [ARG_0] = {"_fs_name", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"fspick",
     433,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"path", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"fstat64",
     215,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"fstatat64",
     293,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"statbuf", 4},
         [ARG_3] = {"flag", 4},
     }},
    {"fstatfs",
     100,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buf", 4},
     }},
    {"fstatfs64",
     256,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"sz", 4},
         [ARG_2] = {"buf", 4},
     }},
    {"fsync",
     118,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
     }},
    {"ftruncate",
     93,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"length", 4},
     }},
    {"ftruncate64",
     212,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"length", 8},
     }},
    {"futex",
     422,
     NORMAL,
     {
         [ARG_0] = {"uaddr", 4},
         [ARG_1] = {"op", 4},
         [ARG_2] = {"val", 4},
         [ARG_3] = {"utime", 4},
         [ARG_4] = {"uaddr2", 4},
         [ARG_5] = {"val3", 4},
     }},
    {"futex_time32",
     238,
     NORMAL,
     {
         [ARG_0] = {"uaddr", 4},
         [ARG_1] = {"op", 4},
         [ARG_2] = {"val", 4},
         [ARG_3] = {"utime", 4},
         [ARG_4] = {"uaddr2", 4},
         [ARG_5] = {"val3", 4},
     }},
    {"futimesat",
     4292,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"utimes", 4},
     }},
    {"futimesat_time32",
     292,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"t", 4},
     }},
    {"get_mempolicy",
     4269,
     NORMAL,
     {
         [ARG_0] = {"policy", 4},
         [ARG_1] = {"nmask", 4},
         [ARG_2] = {"maxnode", 4},
         [ARG_3] = {"addr", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"get_robust_list",
     310,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"head_ptr", 4},
         [ARG_2] = {"len_ptr", 4},
     }},
    {"getcpu",
     312,
     NORMAL,
     {
         [ARG_0] = {"cpup", 4},
         [ARG_1] = {"nodep", 4},
         [ARG_2] = {"unused", 4},
     }},
    {"getcwd",
     203,
     NORMAL,
     {
         [ARG_0] = {"buf", 4},
         [ARG_1] = {"size", 4},
     }},
    {"getdents",
     141,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"dirent", 4},
         [ARG_2] = {"count", 4},
     }},
    {"getdents64",
     219,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"dirent", 4},
         [ARG_2] = {"count", 4},
     }},
    {"getegid", 50, NORMAL, {}},
    {"getegid16", 50, NORMAL, {}},
    {"geteuid", 49, NORMAL, {}},
    {"geteuid16", 49, NORMAL, {}},
    {"getgid", 47, NORMAL, {}},
    {"getgid16", 47, NORMAL, {}},
    {"getgroups",
     80,
     NORMAL,
     {
         [ARG_0] = {"gidsetsize", 4},
         [ARG_1] = {"grouplist", 4},
     }},
    {"getitimer",
     105,
     NORMAL,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"value", 4},
     }},
    {"getpeername",
     171,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"usockaddr", 4},
         [ARG_2] = {"usockaddr_len", 4},
     }},
    {"getpgid",
     132,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
     }},
    {"getpgrp", 65, NORMAL, {}},
    {"getpid", 20, NORMAL, {}},
    {"getppid", 64, NORMAL, {}},
    {"getpriority",
     96,
     NORMAL,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"who", 4},
     }},
    {"getrandom",
     353,
     NORMAL,
     {
         [ARG_0] = {"buf", 4},
         [ARG_1] = {"count", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"getresgid",
     191,
     NORMAL,
     {
         [ARG_0] = {"rgidp", 4},
         [ARG_1] = {"egidp", 4},
         [ARG_2] = {"sgidp", 4},
     }},
    {"getresuid",
     186,
     NORMAL,
     {
         [ARG_0] = {"ruidp", 4},
         [ARG_1] = {"euidp", 4},
         [ARG_2] = {"suidp", 4},
     }},
    {"getrlimit",
     76,
     NORMAL,
     {
         [ARG_0] = {"resource", 4},
         [ARG_1] = {"rlim", 4},
     }},
    {"getrusage",
     77,
     NORMAL,
     {
         [ARG_0] = {"who", 4},
         [ARG_1] = {"ru", 4},
     }},
    {"getsid",
     151,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
     }},
    {"getsockname",
     172,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"usockaddr", 4},
         [ARG_2] = {"usockaddr_len", 4},
     }},
    {"getsockopt",
     173,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"level", 4},
         [ARG_2] = {"optname", 4},
         [ARG_3] = {"optval", 4},
         [ARG_4] = {"optlen", 4},
     }},
    {"gettid", 222, NORMAL, {}},
    {"gettimeofday",
     78,
     NORMAL,
     {
         [ARG_0] = {"tv", 4},
         [ARG_1] = {"tz", 4},
     }},
    {"getuid", 24, NORMAL, {}},
    {"getuid16", 24, NORMAL, {}},
    {"getxattr",
     227,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"value", 4},
         [ARG_3] = {"size", 4},
     }},
    {"init_module",
     128,
     NORMAL,
     {
         [ARG_0] = {"umod", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"uargs", 4},
     }},
    {"inotify_add_watch",
     285,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"mask", 4},
     }},
    {"inotify_init", 284, NORMAL, {}},
    {"inotify_init1",
     329,
     NORMAL,
     {
         [ARG_0] = {"flags", 4},
     }},
    {"inotify_rm_watch",
     286,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"wd", 4},
     }},
    {"io_cancel",
     245,
     NORMAL,
     {
         [ARG_0] = {"ctx_id", 4},
         [ARG_1] = {"iocb", 4},
         [ARG_2] = {"result", 4},
     }},
    {"io_destroy",
     242,
     NORMAL,
     {
         [ARG_0] = {"ctx", 4},
     }},
    {"io_getevents",
     4243,
     NORMAL,
     {
         [ARG_0] = {"ctx_id", 4},
         [ARG_1] = {"min_nr", 4},
         [ARG_2] = {"nr", 4},
         [ARG_3] = {"events", 4},
         [ARG_4] = {"timeout", 4},
     }},
    {"io_getevents_time32",
     243,
     NORMAL,
     {
         [ARG_0] = {"ctx_id", 4},
         [ARG_1] = {"min_nr", 4},
         [ARG_2] = {"nr", 4},
         [ARG_3] = {"events", 4},
         [ARG_4] = {"timeout", 4},
     }},
    {"io_pgetevents",
     416,
     NORMAL,
     {
         [ARG_0] = {"ctx_id", 4},
         [ARG_1] = {"min_nr", 4},
         [ARG_2] = {"nr", 4},
         [ARG_3] = {"events", 4},
         [ARG_4] = {"timeout", 4},
         [ARG_5] = {"usig", 4},
     }},
    {"io_pgetevents_time32",
     368,
     NORMAL,
     {
         [ARG_0] = {"ctx_id", 4},
         [ARG_1] = {"min_nr", 4},
         [ARG_2] = {"nr", 4},
         [ARG_3] = {"events", 4},
         [ARG_4] = {"timeout", 4},
         [ARG_5] = {"usig", 4},
     }},
    {"io_setup",
     241,
     NORMAL,
     {
         [ARG_0] = {"nr_events", 4},
         [ARG_1] = {"ctxp", 4},
     }},
    {"io_submit",
     244,
     NORMAL,
     {
         [ARG_0] = {"ctx_id", 4},
         [ARG_1] = {"nr", 4},
         [ARG_2] = {"iocbpp", 4},
     }},
    {"io_uring_enter",
     426,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"to_submit", 4},
         [ARG_2] = {"min_complete", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"sig", 4},
         [ARG_5] = {"sigsz", 4},
     }},
    {"io_uring_register",
     427,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"opcode", 4},
         [ARG_2] = {"arg", 4},
         [ARG_3] = {"nr_args", 4},
     }},
    {"io_uring_setup",
     425,
     NORMAL,
     {
         [ARG_0] = {"entries", 4},
         [ARG_1] = {"params", 4},
     }},
    {"ioctl",
     54,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"arg", 4},
     }},
    {"ioprio_get",
     315,
     NORMAL,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"who", 4},
     }},
    {"ioprio_set",
     314,
     NORMAL,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"who", 4},
         [ARG_2] = {"ioprio", 4},
     }},
    {"ipc",
     117,
     NORMAL,
     {
         [ARG_0] = {"call", 4},
         [ARG_1] = {"first", 4},
         [ARG_2] = {"second", 4},
         [ARG_3] = {"third", 4},
         [ARG_4] = {"ptr", 4},
         [ARG_5] = {"fifth", 4},
     }},
    {"kcmp",
     347,
     NORMAL,
     {
         [ARG_0] = {"pid1", 4},
         [ARG_1] = {"pid2", 4},
         [ARG_2] = {"type", 4},
         [ARG_3] = {"idx1", 4},
         [ARG_4] = {"idx2", 4},
     }},
    {"kexec_load",
     311,
     NORMAL,
     {
         [ARG_0] = {"entry", 4},
         [ARG_1] = {"nr_segments", 4},
         [ARG_2] = {"segments", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"keyctl",
     282,
     NORMAL,
     {
         [ARG_0] = {"option", 4},
         [ARG_1] = {"arg2", 4},
         [ARG_2] = {"arg3", 4},
         [ARG_3] = {"arg4", 4},
         [ARG_4] = {"arg5", 4},
     }},
    {"kill",
     37,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"sig", 4},
     }},
    {"lchown",
     16,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"user", 4},
         [ARG_2] = {"group", 4},
     }},
    {"lgetxattr",
     228,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"value", 4},
         [ARG_3] = {"size", 4},
     }},
    {"link",
     9,
     NORMAL,
     {
         [ARG_0] = {"oldname", 4},
         [ARG_1] = {"newname", 4},
     }},
    {"linkat",
     296,
     NORMAL,
     {
         [ARG_0] = {"olddfd", 4},
         [ARG_1] = {"oldname", 4},
         [ARG_2] = {"newdfd", 4},
         [ARG_3] = {"newname", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"listen",
     174,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"backlog", 4},
     }},
    {"listxattr",
     230,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"list", 4},
         [ARG_2] = {"size", 4},
     }},
    {"llistxattr",
     231,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"list", 4},
         [ARG_2] = {"size", 4},
     }},
    {"llseek",
     140,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"offset_high", 4},
         [ARG_2] = {"offset_low", 4},
         [ARG_3] = {"result", 4},
         [ARG_4] = {"whence", 4},
     }},
    {"lookup_dcookie",
     247,
     NORMAL,
     {
         [ARG_0] = {"cookie64", 8},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"len", 4},
     }},
    {"lremovexattr",
     234,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"name", 4},
     }},
    {"lseek",
     19,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"offset", 4},
         [ARG_2] = {"whence", 4},
     }},
    {"lsetxattr",
     225,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"value", 4},
         [ARG_3] = {"size", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"lstat64",
     214,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"madvise",
     218,
     NORMAL,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len_in", 4},
         [ARG_2] = {"behavior", 4},
     }},
    {"mbind",
     4268,
     NORMAL,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"mode", 4},
         [ARG_3] = {"nmask", 4},
         [ARG_4] = {"maxnode", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"membarrier",
     358,
     NORMAL,
     {
         [ARG_0] = {"cmd", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"memfd_create",
     354,
     NORMAL,
     {
         [ARG_0] = {"uname", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"mincore",
     217,
     NORMAL,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"vec", 4},
     }},
    {"mips_mmap",
     90,
     NORMAL,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"prot", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"fd", 4},
         [ARG_5] = {"offset", 4},
     }},
    {"mips_mmap2",
     210,
     NORMAL,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"prot", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"fd", 4},
         [ARG_5] = {"pgoff", 4},
     }},
    {"mkdir",
     39,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"mode", 2},
     }},
    {"mkdirat",
     289,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"mode", 2},
     }},
    {"mknod",
     14,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"mode", 2},
         [ARG_2] = {"dev", 4},
     }},
    {"mknodat",
     290,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"mode", 2},
         [ARG_3] = {"dev", 4},
     }},
    {"mlock",
     154,
     NORMAL,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
     }},
    {"mlock2",
     359,
     NORMAL,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"mlockall",
     156,
     NORMAL,
     {
         [ARG_0] = {"flags", 4},
     }},
    {"mmap",
     4090,
     NORMAL,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"prot", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"fd", 4},
         [ARG_5] = {"offset", 4},
     }}, // obsolete, no longer available for EABI
    {"mmap2",
     4210,
     NORMAL,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"prot", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"fd", 4},
         [ARG_5] = {"pgoffset", 4},
     }},
    {"mount",
     21,
     NORMAL,
     {
         [ARG_0] = {"dev_name", 4},
         [ARG_1] = {"dir_name", 4},
         [ARG_2] = {"type", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"data", 4},
     }},
    {"move_mount",
     429,
     NORMAL,
     {
         [ARG_0] = {"from_dfd", 4},
         [ARG_1] = {"from_pathname", 4},
         [ARG_2] = {"to_dfd", 4},
         [ARG_3] = {"to_pathname", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"move_pages",
     4308,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"nr_pages", 4},
         [ARG_2] = {"pages", 4},
         [ARG_3] = {"nodes", 4},
         [ARG_4] = {"status", 4},
         [ARG_5] = {"flag", 4},
     }},
    {"mprotect",
     125,
     NORMAL,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"prot", 4},
     }},
    {"mq_getsetattr",
     276,
     NORMAL,
     {
         [ARG_0] = {"mqdes", 4},
         [ARG_1] = {"u_mqstat", 4},
         [ARG_2] = {"u_omqstat", 4},
     }},
    {"mq_notify",
     275,
     NORMAL,
     {
         [ARG_0] = {"mqdes", 4},
         [ARG_1] = {"u_notification", 4},
     }},
    {"mq_open",
     271,
     NORMAL,
     {
         [ARG_0] = {"u_name", 4},
         [ARG_1] = {"oflag", 4},
         [ARG_2] = {"mode", 2},
         [ARG_3] = {"u_attr", 4},
     }},
    {"mq_timedreceive",
     419,
     NORMAL,
     {
         [ARG_0] = {"mqdes", 4},
         [ARG_1] = {"u_msg_ptr", 4},
         [ARG_2] = {"msg_len", 4},
         [ARG_3] = {"u_msg_prio", 4},
         [ARG_4] = {"u_abs_timeout", 4},
     }},
    {"mq_timedreceive_time32",
     274,
     NORMAL,
     {
         [ARG_0] = {"mqdes", 4},
         [ARG_1] = {"u_msg_ptr", 4},
         [ARG_2] = {"msg_len", 4},
         [ARG_3] = {"u_msg_prio", 4},
         [ARG_4] = {"u_abs_timeout", 4},
     }},
    {"mq_timedsend",
     418,
     NORMAL,
     {
         [ARG_0] = {"mqdes", 4},
         [ARG_1] = {"u_msg_ptr", 4},
         [ARG_2] = {"msg_len", 4},
         [ARG_3] = {"msg_prio", 4},
         [ARG_4] = {"u_abs_timeout", 4},
     }},
    {"mq_timedsend_time32",
     273,
     NORMAL,
     {
         [ARG_0] = {"mqdes", 4},
         [ARG_1] = {"u_msg_ptr", 4},
         [ARG_2] = {"msg_len", 4},
         [ARG_3] = {"msg_prio", 4},
         [ARG_4] = {"u_abs_timeout", 4},
     }},
    {"mq_unlink",
     272,
     NORMAL,
     {
         [ARG_0] = {"u_name", 4},
     }},
    {"mremap",
     167,
     NORMAL,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"old_len", 4},
         [ARG_2] = {"new_len", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"new_addr", 4},
     }},
    {"msgctl",
     402,
     NORMAL,
     {
         [ARG_0] = {"msqid", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"buf", 4},
     }},
    {"msgget",
     399,
     NORMAL,
     {
         [ARG_0] = {"key", 4},
         [ARG_1] = {"msgflg", 4},
     }},
    {"msgrcv",
     401,
     NORMAL,
     {
         [ARG_0] = {"msqid", 4},
         [ARG_1] = {"msgp", 4},
         [ARG_2] = {"msgsz", 4},
         [ARG_3] = {"msgtyp", 4},
         [ARG_4] = {"msgflg", 4},
     }},
    {"msgsnd",
     400,
     NORMAL,
     {
         [ARG_0] = {"msqid", 4},
         [ARG_1] = {"msgp", 4},
         [ARG_2] = {"msgsz", 4},
         [ARG_3] = {"msgflg", 4},
     }},
    {"msync",
     144,
     NORMAL,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"munlock",
     155,
     NORMAL,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"len", 4},
     }},
    {"munlockall", 157, NORMAL, {}},
    {"munmap",
     91,
     NORMAL,
     {
         [ARG_0] = {"addr", 4},
         [ARG_1] = {"len", 4},
     }},
    {"name_to_handle_at",
     339,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"handle", 4},
         [ARG_3] = {"mnt_id", 4},
         [ARG_4] = {"flag", 4},
     }},
    {"nanosleep",
     4166,
     NORMAL,
     {
         [ARG_0] = {"rqtp", 4},
         [ARG_1] = {"rmtp", 4},
     }},
    {"nanosleep_time32",
     166,
     NORMAL,
     {
         [ARG_0] = {"rqtp", 4},
         [ARG_1] = {"rmtp", 4},
     }},
    {"newfstat",
     108,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"newlstat",
     107,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"newstat",
     106,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"newuname",
     122,
     NORMAL,
     {
         [ARG_0] = {"name", 4},
     }},
    {"nfsservctl",
     4189,
     NORMAL,
     {
         [ARG_0] = {"cmd", 4},
         [ARG_1] = {"argp", 4},
         [ARG_2] = {"resp", 4},
     }},
    {"nice",
     34,
     NORMAL,
     {
         [ARG_0] = {"increment", 4},
     }},
    {"old_readdir",
     89,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"dirent", 4},
         [ARG_2] = {"count", 4},
     }},
    {"oldumount",
     22,
     NORMAL,
     {
         [ARG_0] = {"name", 4},
     }},
    {"olduname",
     59,
     NORMAL,
     {
         [ARG_0] = {"name", 4},
     }},
    {"open",
     5,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"mode", 2},
     }},
    {"open_by_handle_at",
     340,
     NORMAL,
     {
         [ARG_0] = {"mountdirfd", 4},
         [ARG_1] = {"handle", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"open_tree",
     428,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"openat",
     288,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"flags", 4},
         [ARG_3] = {"mode", 2},
     }},
    {"openat2",
     437,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"how", 4},
         [ARG_3] = {"usize", 4},
     }},
    {"pause", 29, NORMAL, {}},
    {"perf_event_open",
     333,
     NORMAL,
     {
         [ARG_0] = {"attr_uptr", 4},
         [ARG_1] = {"pid", 4},
         [ARG_2] = {"cpu", 4},
         [ARG_3] = {"group_fd", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"personality",
     136,
     NORMAL,
     {
         [ARG_0] = {"personality", 4},
     }},
    {"pidfd_getfd",
     438,
     NORMAL,
     {
         [ARG_0] = {"pidfd", 4},
         [ARG_1] = {"fd", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"pidfd_open",
     434,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"pidfd_send_signal",
     424,
     NORMAL,
     {
         [ARG_0] = {"pidfd", 4},
         [ARG_1] = {"sig", 4},
         [ARG_2] = {"info", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"pipe",
     4042,
     NORMAL,
     {
         [ARG_0] = {"fildes", 4},
     }},
    {"pipe2",
     328,
     NORMAL,
     {
         [ARG_0] = {"fildes", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"pivot_root",
     216,
     NORMAL,
     {
         [ARG_0] = {"new_root", 4},
         [ARG_1] = {"put_old", 4},
     }},
    {"poll",
     188,
     NORMAL,
     {
         [ARG_0] = {"ufds", 4},
         [ARG_1] = {"nfds", 4},
         [ARG_2] = {"timeout_msecs", 4},
     }},
    {"ppoll",
     414,
     NORMAL,
     {
         [ARG_0] = {"ufds", 4},
         [ARG_1] = {"nfds", 4},
         [ARG_2] = {"tsp", 4},
         [ARG_3] = {"sigmask", 4},
         [ARG_4] = {"sigsetsize", 4},
     }},
    {"ppoll_time32",
     302,
     NORMAL,
     {
         [ARG_0] = {"ufds", 4},
         [ARG_1] = {"nfds", 4},
         [ARG_2] = {"tsp", 4},
         [ARG_3] = {"sigmask", 4},
         [ARG_4] = {"sigsetsize", 4},
     }},
    {"prctl",
     192,
     NORMAL,
     {
         [ARG_0] = {"option", 4},
         [ARG_1] = {"arg2", 4},
         [ARG_2] = {"arg3", 4},
         [ARG_3] = {"arg4", 4},
         [ARG_4] = {"arg5", 4},
     }},
    {"pread64",
     200,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"count", 4},
         [ARG_3] = {"pos", 8},
     }},
    {"preadv",
     330,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"pos_l", 4},
         [ARG_4] = {"pos_h", 4},
     }},
    {"preadv2",
     361,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"pos_l", 4},
         [ARG_4] = {"pos_h", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"prlimit64",
     338,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"resource", 4},
         [ARG_2] = {"new_rlim", 4},
         [ARG_3] = {"old_rlim", 4},
     }},
    {"process_vm_readv",
     345,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"lvec", 4},
         [ARG_2] = {"liovcnt", 4},
         [ARG_3] = {"rvec", 4},
         [ARG_4] = {"riovcnt", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"process_vm_writev",
     346,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"lvec", 4},
         [ARG_2] = {"liovcnt", 4},
         [ARG_3] = {"rvec", 4},
         [ARG_4] = {"riovcnt", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"pselect6",
     413,
     NORMAL,
     {
         [ARG_0] = {"n", 4},
         [ARG_1] = {"inp", 4},
         [ARG_2] = {"outp", 4},
         [ARG_3] = {"exp", 4},
         [ARG_4] = {"tsp", 4},
         [ARG_5] = {"sig", 4},
     }},
    {"pselect6_time32",
     301,
     NORMAL,
     {
         [ARG_0] = {"n", 4},
         [ARG_1] = {"inp", 4},
         [ARG_2] = {"outp", 4},
         [ARG_3] = {"exp", 4},
         [ARG_4] = {"tsp", 4},
         [ARG_5] = {"sig", 4},
     }},
    {"ptrace",
     26,
     NORMAL,
     {
         [ARG_0] = {"request", 4},
         [ARG_1] = {"pid", 4},
         [ARG_2] = {"addr", 4},
         [ARG_3] = {"data", 4},
     }},
    {"pwrite64",
     201,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"count", 4},
         [ARG_3] = {"pos", 8},
     }},
    {"pwritev",
     331,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"pos_l", 4},
         [ARG_4] = {"pos_h", 4},
     }},
    {"pwritev2",
     362,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"pos_l", 4},
         [ARG_4] = {"pos_h", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"quotactl",
     131,
     NORMAL,
     {
         [ARG_0] = {"cmd", 4},
         [ARG_1] = {"special", 4},
         [ARG_2] = {"id", 4},
         [ARG_3] = {"addr", 4},
     }},
    {"read",
     3,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"count", 4},
     }},
    {"readahead",
     223,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"offset", 8},
         [ARG_2] = {"count", 4},
     }},
    {"readdir",
     4089,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"dirent", 4},
         [ARG_2] = {"count", 4},
     }}, // obsolete, no longer available for EABI
    {"readlink",
     85,
     NORMAL,
     {
         [ARG_0] = {"path", 4},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"bufsiz", 4},
     }},
    {"readlinkat",
     298,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"buf", 4},
         [ARG_3] = {"bufsiz", 4},
     }},
    {"readv",
     145,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
     }},
    {"reboot",
     88,
     NORMAL,
     {
         [ARG_0] = {"magic1", 4},
         [ARG_1] = {"magic2", 4},
         [ARG_2] = {"cmd", 4},
         [ARG_3] = {"arg", 4},
     }},
    {"recv",
     175,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"ubuf", 4},
         [ARG_2] = {"size", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"recvfrom",
     176,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"ubuf", 4},
         [ARG_2] = {"size", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"addr", 4},
         [ARG_5] = {"addr_len", 4},
     }},
    {"recvmmsg",
     417,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"mmsg", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"timeout", 4},
     }},
    {"recvmmsg_time32",
     335,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"mmsg", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"timeout", 4},
     }},
    {"recvmsg",
     177,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"msg", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"remap_file_pages",
     251,
     NORMAL,
     {
         [ARG_0] = {"start", 4},
         [ARG_1] = {"size", 4},
         [ARG_2] = {"prot", 4},
         [ARG_3] = {"pgoff", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"removexattr",
     233,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"name", 4},
     }},
    {"rename",
     38,
     NORMAL,
     {
         [ARG_0] = {"oldname", 4},
         [ARG_1] = {"newname", 4},
     }},
    {"renameat",
     295,
     NORMAL,
     {
         [ARG_0] = {"olddfd", 4},
         [ARG_1] = {"oldname", 4},
         [ARG_2] = {"newdfd", 4},
         [ARG_3] = {"newname", 4},
     }},
    {"renameat2",
     351,
     NORMAL,
     {
         [ARG_0] = {"olddfd", 4},
         [ARG_1] = {"oldname", 4},
         [ARG_2] = {"newdfd", 4},
         [ARG_3] = {"newname", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"request_key",
     281,
     NORMAL,
     {
         [ARG_0] = {"_type", 4},
         [ARG_1] = {"_description", 4},
         [ARG_2] = {"_callout_info", 4},
         [ARG_3] = {"destringid", 4},
     }},
    {"restart_syscall", 253, NORMAL, {}},
    {"rmdir",
     40,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
     }},
    {"rseq",
     367,
     NORMAL,
     {
         [ARG_0] = {"rseq", 4},
         [ARG_1] = {"rseq_len", 4},
         [ARG_2] = {"flags", 4},
         [ARG_3] = {"sig", 4},
     }},
    {"rt_sigaction",
     194,
     NORMAL,
     {
         [ARG_0] = {"sig", 4},
         [ARG_1] = {"act", 4},
         [ARG_2] = {"oact", 4},
         [ARG_3] = {"sigsetsize", 4},
     }},
    {"rt_sigpending",
     196,
     NORMAL,
     {
         [ARG_0] = {"uset", 4},
         [ARG_1] = {"sigsetsize", 4},
     }},
    {"rt_sigprocmask",
     195,
     NORMAL,
     {
         [ARG_0] = {"how", 4},
         [ARG_1] = {"nset", 4},
         [ARG_2] = {"oset", 4},
         [ARG_3] = {"sigsetsize", 4},
     }},
    {"rt_sigqueueinfo",
     198,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"sig", 4},
         [ARG_2] = {"uinfo", 4},
     }},
    {"rt_sigreturn", 173, NORMAL, {}},
    {"rt_sigsuspend",
     199,
     NORMAL,
     {
         [ARG_0] = {"unewset", 4},
         [ARG_1] = {"sigsetsize", 4},
     }},
    {"rt_sigtimedwait",
     421,
     NORMAL,
     {
         [ARG_0] = {"uthese", 4},
         [ARG_1] = {"uinfo", 4},
         [ARG_2] = {"uts", 4},
         [ARG_3] = {"sigsetsize", 4},
     }},
    {"rt_sigtimedwait_time32",
     197,
     NORMAL,
     {
         [ARG_0] = {"uthese", 4},
         [ARG_1] = {"uinfo", 4},
         [ARG_2] = {"uts", 4},
         [ARG_3] = {"sigsetsize", 4},
     }},
    {"rt_tgsigqueueinfo",
     332,
     NORMAL,
     {
         [ARG_0] = {"tgid", 4},
         [ARG_1] = {"pid", 4},
         [ARG_2] = {"sig", 4},
         [ARG_3] = {"uinfo", 4},
     }},
    {"sched_get_priority_max",
     163,
     NORMAL,
     {
         [ARG_0] = {"policy", 4},
     }},
    {"sched_get_priority_min",
     164,
     NORMAL,
     {
         [ARG_0] = {"policy", 4},
     }},
    {"sched_getaffinity",
     240,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"user_mask_ptr", 4},
     }},
    {"sched_getattr",
     350,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"uattr", 4},
         [ARG_2] = {"usize", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"sched_getparam",
     159,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"param", 4},
     }},
    {"sched_getscheduler",
     161,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
     }},
    {"sched_rr_get_interval",
     423,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"interval", 4},
     }},
    {"sched_rr_get_interval_time32",
     165,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"interval", 4},
     }},
    {"sched_setaffinity",
     239,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"len", 4},
         [ARG_2] = {"user_mask_ptr", 4},
     }},
    {"sched_setattr",
     349,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"uattr", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"sched_setparam",
     158,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"param", 4},
     }},
    {"sched_setscheduler",
     160,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"policy", 4},
         [ARG_2] = {"param", 4},
     }},
    {"sched_yield", 162, NORMAL, {}},
    {"seccomp",
     352,
     NORMAL,
     {
         [ARG_0] = {"op", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"uargs", 4},
     }},
    {"select",
     142,
     NORMAL,
     {
         [ARG_0] = {"n", 4},
         [ARG_1] = {"inp", 4},
         [ARG_2] = {"outp", 4},
         [ARG_3] = {"exp", 4},
         [ARG_4] = {"tvp", 4},
     }},
    {"semctl",
     394,
     NORMAL,
     {
         [ARG_0] = {"semid", 4},
         [ARG_1] = {"semnum", 4},
         [ARG_2] = {"cmd", 4},
         [ARG_3] = {"arg", 4},
     }},
    {"semget",
     393,
     NORMAL,
     {
         [ARG_0] = {"key", 4},
         [ARG_1] = {"nsems", 4},
         [ARG_2] = {"semflg", 4},
     }},
    {"semtimedop",
     420,
     NORMAL,
     {
         [ARG_0] = {"semid", 4},
         [ARG_1] = {"tsops", 4},
         [ARG_2] = {"nsops", 4},
         [ARG_3] = {"timeout", 4},
     }},
    {"send",
     178,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buff", 4},
         [ARG_2] = {"len", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"sendfile",
     207,
     NORMAL,
     {
         [ARG_0] = {"out_fd", 4},
         [ARG_1] = {"in_fd", 4},
         [ARG_2] = {"offset", 4},
         [ARG_3] = {"count", 4},
     }},
    {"sendfile64",
     237,
     NORMAL,
     {
         [ARG_0] = {"out_fd", 4},
         [ARG_1] = {"in_fd", 4},
         [ARG_2] = {"offset", 4},
         [ARG_3] = {"count", 4},
     }},
    {"sendmmsg",
     343,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"mmsg", 4},
         [ARG_2] = {"vlen", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"sendmsg",
     179,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"msg", 4},
         [ARG_2] = {"flags", 4},
     }},
    {"sendto",
     180,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buff", 4},
         [ARG_2] = {"len", 4},
         [ARG_3] = {"flags", 4},
         [ARG_4] = {"addr", 4},
         [ARG_5] = {"addr_len", 4},
     }},
    {"set_mempolicy",
     4270,
     NORMAL,
     {
         [ARG_0] = {"mode", 4},
         [ARG_1] = {"nmask", 4},
         [ARG_2] = {"maxnode", 4},
     }},
    {"set_robust_list",
     309,
     NORMAL,
     {
         [ARG_0] = {"head", 4},
         [ARG_1] = {"len", 4},
     }},
    {"set_thread_area",
     283,
     NORMAL,
     {
         [ARG_0] = {"addr", 4},
     }},
    {"set_tid_address",
     252,
     NORMAL,
     {
         [ARG_0] = {"tidptr", 4},
     }},
    {"setdomainname",
     121,
     NORMAL,
     {
         [ARG_0] = {"name", 4},
         [ARG_1] = {"len", 4},
     }},
    {"setfsgid",
     139,
     NORMAL,
     {
         [ARG_0] = {"gid", 4},
     }},
    {"setfsuid",
     138,
     NORMAL,
     {
         [ARG_0] = {"uid", 4},
     }},
    {"setgid",
     46,
     NORMAL,
     {
         [ARG_0] = {"gid", 4},
     }},
    {"setgroups",
     81,
     NORMAL,
     {
         [ARG_0] = {"gidsetsize", 4},
         [ARG_1] = {"grouplist", 4},
     }},
    {"sethostname",
     74,
     NORMAL,
     {
         [ARG_0] = {"name", 4},
         [ARG_1] = {"len", 4},
     }},
    {"setitimer",
     104,
     NORMAL,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"value", 4},
         [ARG_2] = {"ovalue", 4},
     }},
    {"setns",
     344,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"setpgid",
     57,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"pgid", 4},
     }},
    {"setpriority",
     97,
     NORMAL,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"who", 4},
         [ARG_2] = {"niceval", 4},
     }},
    {"setregid",
     71,
     NORMAL,
     {
         [ARG_0] = {"rgid", 4},
         [ARG_1] = {"egid", 4},
     }},
    {"setresgid",
     190,
     NORMAL,
     {
         [ARG_0] = {"rgid", 4},
         [ARG_1] = {"egid", 4},
         [ARG_2] = {"sgid", 4},
     }},
    {"setresuid",
     185,
     NORMAL,
     {
         [ARG_0] = {"ruid", 4},
         [ARG_1] = {"euid", 4},
         [ARG_2] = {"suid", 4},
     }},
    {"setreuid",
     70,
     NORMAL,
     {
         [ARG_0] = {"ruid", 4},
         [ARG_1] = {"euid", 4},
     }},
    {"setrlimit",
     75,
     NORMAL,
     {
         [ARG_0] = {"resource", 4},
         [ARG_1] = {"rlim", 4},
     }},
    {"setsid", 66, NORMAL, {}},
    {"setsockopt",
     181,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"level", 4},
         [ARG_2] = {"optname", 4},
         [ARG_3] = {"optval", 4},
         [ARG_4] = {"optlen", 4},
     }},
    {"settimeofday",
     79,
     NORMAL,
     {
         [ARG_0] = {"tv", 4},
         [ARG_1] = {"tz", 4},
     }},
    {"setuid",
     23,
     NORMAL,
     {
         [ARG_0] = {"uid", 4},
     }},
    {"setxattr",
     224,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"name", 4},
         [ARG_2] = {"value", 4},
         [ARG_3] = {"size", 4},
         [ARG_4] = {"flags", 4},
     }},
    {"sgetmask", 68, NORMAL, {}},
    {"shmat",
     397,
     NORMAL,
     {
         [ARG_0] = {"shmid", 4},
         [ARG_1] = {"shmaddr", 4},
         [ARG_2] = {"shmflg", 4},
     }},
    {"shmctl",
     396,
     NORMAL,
     {
         [ARG_0] = {"shmid", 4},
         [ARG_1] = {"cmd", 4},
         [ARG_2] = {"buf", 4},
     }},
    {"shmdt",
     398,
     NORMAL,
     {
         [ARG_0] = {"shmaddr", 4},
     }},
    {"shmget",
     395,
     NORMAL,
     {
         [ARG_0] = {"key", 4},
         [ARG_1] = {"size", 4},
         [ARG_2] = {"shmflg", 4},
     }},
    {"shutdown",
     182,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"how", 4},
     }},
    {"sigaction",
     67,
     NORMAL,
     {
         [ARG_0] = {"sig", 4},
         [ARG_1] = {"act", 4},
         [ARG_2] = {"oact", 4},
     }},
    {"sigaltstack",
     206,
     NORMAL,
     {
         [ARG_0] = {"uss", 4},
         [ARG_1] = {"uoss", 4},
     }},
    {"signalfd",
     317,
     NORMAL,
     {
         [ARG_0] = {"ufd", 4},
         [ARG_1] = {"user_mask", 4},
         [ARG_2] = {"sizemask", 4},
     }},
    {"signalfd4",
     324,
     NORMAL,
     {
         [ARG_0] = {"ufd", 4},
         [ARG_1] = {"user_mask", 4},
         [ARG_2] = {"sizemask", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"sigpending",
     73,
     NORMAL,
     {
         [ARG_0] = {"uset", 4},
     }},
    {"sigprocmask",
     126,
     NORMAL,
     {
         [ARG_0] = {"how", 4},
         [ARG_1] = {"nset", 4},
         [ARG_2] = {"oset", 4},
     }},
    {"sigreturn", 119, NORMAL, {}},
    {"sigsuspend",
     72,
     NORMAL,
     {
         [ARG_0] = {"uset", 4},
     }},
    {"socket",
     183,
     NORMAL,
     {
         [ARG_0] = {"family", 4},
         [ARG_1] = {"type", 4},
         [ARG_2] = {"protocol", 4},
     }},
    {"socketcall",
     102,
     NORMAL,
     {
         [ARG_0] = {"call", 4},
         [ARG_1] = {"args", 4},
     }},
    {"socketpair",
     184,
     NORMAL,
     {
         [ARG_0] = {"family", 4},
         [ARG_1] = {"type", 4},
         [ARG_2] = {"protocol", 4},
         [ARG_3] = {"usockvec", 4},
     }},
    {"splice",
     304,
     NORMAL,
     {
         [ARG_0] = {"fd_in", 4},
         [ARG_1] = {"off_in", 4},
         [ARG_2] = {"fd_out", 4},
         [ARG_3] = {"off_out", 4},
         [ARG_4] = {"len", 4},
         [ARG_5] = {"flags", 4},
     }},
    {"ssetmask",
     69,
     NORMAL,
     {
         [ARG_0] = {"newmask", 4},
     }},
    {"stat64",
     213,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"statbuf", 4},
     }},
    {"statfs",
     99,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"buf", 4},
     }},
    {"statfs64",
     255,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
         [ARG_1] = {"sz", 4},
         [ARG_2] = {"buf", 4},
     }},
    {"statx",
     366,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"flags", 4},
         [ARG_3] = {"mask", 4},
         [ARG_4] = {"buffer", 4},
     }},
    {"stime",
     4025,
     NORMAL,
     {
         [ARG_0] = {"tptr", 4},
     }}, // obsolete, no longer available for EABI
    {"stime32",
     25,
     NORMAL,
     {
         [ARG_0] = {"tptr", 4},
     }},
    {"swapoff",
     115,
     NORMAL,
     {
         [ARG_0] = {"specialfile", 4},
     }},
    {"swapon",
     87,
     NORMAL,
     {
         [ARG_0] = {"specialfile", 4},
         [ARG_1] = {"swap_flags", 4},
     }},
    {"symlink",
     83,
     NORMAL,
     {
         [ARG_0] = {"oldname", 4},
         [ARG_1] = {"newname", 4},
     }},
    {"symlinkat",
     297,
     NORMAL,
     {
         [ARG_0] = {"oldname", 4},
         [ARG_1] = {"newdfd", 4},
         [ARG_2] = {"newname", 4},
     }},
    {"sync", 36, NORMAL, {}},
    {"sync_file_range",
     305,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"offset", 8},
         [ARG_2] = {"nbytes", 8},
         [ARG_3] = {"flags", 4},
     }},
    {"syncfs",
     342,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
     }},
    {"syscall", 113, NORMAL, {}}, // obsolete, no longer available for EABI
    {"sysctl",
     153,
     NORMAL,
     {
         [ARG_0] = {"args", 4},
     }},
    {"sysfs",
     135,
     NORMAL,
     {
         [ARG_0] = {"option", 4},
         [ARG_1] = {"arg1", 4},
         [ARG_2] = {"arg2", 4},
     }},
    {"sysinfo",
     116,
     NORMAL,
     {
         [ARG_0] = {"info", 4},
     }},
    {"syslog",
     103,
     NORMAL,
     {
         [ARG_0] = {"type", 4},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"len", 4},
     }},
    {"sysmips",
     149,
     NORMAL,
     {
         [ARG_0] = {"cmd", 4},
         [ARG_1] = {"arg1", 4},
         [ARG_2] = {"arg2", 4},
     }},
    {"tee",
     306,
     NORMAL,
     {
         [ARG_0] = {"fdin", 4},
         [ARG_1] = {"fdout", 4},
         [ARG_2] = {"len", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"tgkill",
     266,
     NORMAL,
     {
         [ARG_0] = {"tgid", 4},
         [ARG_1] = {"pid", 4},
         [ARG_2] = {"sig", 4},
     }},
    {"time",
     4013,
     NORMAL,
     {
         [ARG_0] = {"tloc", 4},
     }}, // obsolete, no longer available for EABI
    {"time32",
     13,
     NORMAL,
     {
         [ARG_0] = {"tloc", 4},
     }},
    {"timer_create",
     257,
     NORMAL,
     {
         [ARG_0] = {"which_clock", 4},
         [ARG_1] = {"timer_event_spec", 4},
         [ARG_2] = {"created_timer_id", 4},
     }},
    {"timer_delete",
     261,
     NORMAL,
     {
         [ARG_0] = {"timer_id", 4},
     }},
    {"timer_getoverrun",
     260,
     NORMAL,
     {
         [ARG_0] = {"timer_id", 4},
     }},
    {"timer_gettime",
     408,
     NORMAL,
     {
         [ARG_0] = {"timer_id", 4},
         [ARG_1] = {"setting", 4},
     }},
    {"timer_gettime32",
     259,
     NORMAL,
     {
         [ARG_0] = {"timer_id", 4},
         [ARG_1] = {"setting", 4},
     }},
    {"timer_settime",
     409,
     NORMAL,
     {
         [ARG_0] = {"timer_id", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"new_setting", 4},
         [ARG_3] = {"old_setting", 4},
     }},
    {"timer_settime32",
     258,
     NORMAL,
     {
         [ARG_0] = {"timer_id", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"new", 4},
         [ARG_3] = {"old", 4},
     }},
    {"timerfd_create",
     321,
     NORMAL,
     {
         [ARG_0] = {"clockid", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"timerfd_gettime",
     410,
     NORMAL,
     {
         [ARG_0] = {"ufd", 4},
         [ARG_1] = {"otmr", 4},
     }},
    {"timerfd_gettime32",
     322,
     NORMAL,
     {
         [ARG_0] = {"ufd", 4},
         [ARG_1] = {"otmr", 4},
     }},
    {"timerfd_settime",
     411,
     NORMAL,
     {
         [ARG_0] = {"ufd", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"utmr", 4},
         [ARG_3] = {"otmr", 4},
     }},
    {"timerfd_settime32",
     323,
     NORMAL,
     {
         [ARG_0] = {"ufd", 4},
         [ARG_1] = {"flags", 4},
         [ARG_2] = {"utmr", 4},
         [ARG_3] = {"otmr", 4},
     }},
    {"times",
     43,
     NORMAL,
     {
         [ARG_0] = {"tbuf", 4},
     }},
    {"tkill",
     236,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"sig", 4},
     }},
    {"truncate",
     92,
     NORMAL,
     {
         [ARG_0] = {"path", 4},
         [ARG_1] = {"length", 4},
     }},
    {"truncate64",
     211,
     NORMAL,
     {
         [ARG_0] = {"path", 4},
         [ARG_1] = {"length", 8},
     }},
    {"umask",
     60,
     NORMAL,
     {
         [ARG_0] = {"mask", 4},
     }},
    {"umount",
     52,
     NORMAL,
     {
         [ARG_0] = {"name", 4},
         [ARG_1] = {"flags", 4},
     }},
    {"uname",
     109,
     NORMAL,
     {
         [ARG_0] = {"name", 4},
     }},
    {"unlink",
     10,
     NORMAL,
     {
         [ARG_0] = {"pathname", 4},
     }},
    {"unlinkat",
     294,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"pathname", 4},
         [ARG_2] = {"flag", 4},
     }},
    {"unshare",
     303,
     NORMAL,
     {
         [ARG_0] = {"unshare_flags", 4},
     }},
    {"uselib",
     4086,
     NORMAL,
     {
         [ARG_0] = {"library", 4},
     }},
    {"userfaultfd",
     357,
     NORMAL,
     {
         [ARG_0] = {"flags", 4},
     }},
    {"usr26", 983043, NORMAL, {}},
    {"usr32", 983044, NORMAL, {}},
    {"ustat",
     62,
     NORMAL,
     {
         [ARG_0] = {"dev", 4},
         [ARG_1] = {"ubuf", 4},
     }},
    {"utime",
     4030,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"times", 4},
     }},
    {"utime32",
     30,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"t", 4},
     }},
    {"utimensat",
     412,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"utimes", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"utimensat_time32",
     316,
     NORMAL,
     {
         [ARG_0] = {"dfd", 4},
         [ARG_1] = {"filename", 4},
         [ARG_2] = {"t", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"utimes",
     4267,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"utimes", 4},
     }},
    {"utimes_time32",
     267,
     NORMAL,
     {
         [ARG_0] = {"filename", 4},
         [ARG_1] = {"t", 4},
     }},
    {"vfork", 190, NORMAL, {}},
    {"vhangup", 111, NORMAL, {}},
    {"vmsplice",
     307,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"uiov", 4},
         [ARG_2] = {"nr_segs", 4},
         [ARG_3] = {"flags", 4},
     }},
    {"vserver", 313, NORMAL, {}}, // unimplemented system call
    {"wait4",
     114,
     NORMAL,
     {
         [ARG_0] = {"upid", 4},
         [ARG_1] = {"stat_addr", 4},
         [ARG_2] = {"options", 4},
         [ARG_3] = {"ru", 4},
     }},
    {"waitid",
     278,
     NORMAL,
     {
         [ARG_0] = {"which", 4},
         [ARG_1] = {"upid", 4},
         [ARG_2] = {"infop", 4},
         [ARG_3] = {"options", 4},
         [ARG_4] = {"ru", 4},
     }},
    {"waitpid",
     7,
     NORMAL,
     {
         [ARG_0] = {"pid", 4},
         [ARG_1] = {"stat_addr", 4},
         [ARG_2] = {"options", 4},
     }},
    {"write",
     4,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"buf", 4},
         [ARG_2] = {"count", 4},
     }},
    {"writev",
     146,
     NORMAL,
     {
         [ARG_0] = {"fd", 4},
         [ARG_1] = {"vec", 4},
         [ARG_2] = {"vlen", 4},
     }},
};

const size_t mipso32_syscall_list_size =
    sizeof(mipso32_syscall_list) / sizeof(mipso32_syscall_list[0]);
