	{"adjtimex", 124, NORMAL, {[ARG_0] = {"txc_p", 4},}},
	{"fadvise64", 250, NORMAL, {[ARG_0] = {"fd", 4}, [ARG_1] = {"offset", 8}, [ARG_2] = {"len", 4}, [ARG_3] = {"advice", 4},}},
	{"fadvise64_64", 272, NORMAL, {[ARG_0] = {"fd", 4}, [ARG_1] = {"offset", 8}, [ARG_2] = {"len", 8}, [ARG_3] = {"advice", 4},}},
	{"fallocate", 324, NORMAL, {[ARG_0] = {"fd", 4}, [ARG_1] = {"mode", 4}, [ARG_2] = {"offset", 8}, [ARG_3] = {"len", 8},}},
	{"ftruncate64", 194, NORMAL, {[ARG_0] = {"fd", 4}, [ARG_1] = {"length", 8},}},
	{"futimesat", 299, NORMAL, {[ARG_0] = {"dfd", 4}, [ARG_1] = {"filename", 4}, [ARG_2] = {"utimes", 4},}},
	{"io_getevents", 247, NORMAL, {[ARG_0] = {"ctx_id", 4}, [ARG_1] = {"min_nr", 4}, [ARG_2] = {"nr", 4}, [ARG_3] = {"events", 4}, [ARG_4] = {"timeout", 4},}},
	{"nanosleep", 162, NORMAL, {[ARG_0] = {"rqtp", 4}, [ARG_1] = {"rmtp", 4},}},
	{"pread64", 180, NORMAL, {[ARG_0] = {"fd", 4}, [ARG_1] = {"buf", 4}, [ARG_2] = {"count", 4}, [ARG_3] = {"pos", 8},}},
	{"pwrite64", 181, NORMAL, {[ARG_0] = {"fd", 4}, [ARG_1] = {"buf", 4}, [ARG_2] = {"count", 4}, [ARG_3] = {"pos", 8},}},
	{"readahead", 225, NORMAL, {[ARG_0] = {"fd", 4}, [ARG_1] = {"offset", 8}, [ARG_2] = {"count", 4},}},
	{"stime", 25, NORMAL, {[ARG_0] = {"tptr", 4},}},
	{"sync_file_range", 314, NORMAL, {[ARG_0] = {"fd", 4}, [ARG_1] = {"offset", 8}, [ARG_2] = {"nbytes", 8}, [ARG_3] = {"flags", 4},}},
	{"time", 13, NORMAL, {[ARG_0] = {"tloc", 4},}},
	{"truncate64", 193, NORMAL, {[ARG_0] = {"path", 4}, [ARG_1] = {"length", 8},}},
	{"utime", 30, NORMAL, {[ARG_0] = {"filename", 4}, [ARG_1] = {"times", 4},}},
	{"utimes", 271, NORMAL, {[ARG_0] = {"filename", 4}, [ARG_1] = {"utimes", 4},}},
	{"vm86", 166,  NORMAL, {[ARG_0] = {"cmd", 4}, [ARG_1] = {"arg", 4},}},
	{"vm86old", 113, NORMAL, {[ARG_0] = {"user_vm86", 4},}},

